from pathlib import Path
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from pypdf import PdfReader
ROOT=Path(__file__).resolve().parents[4]
OUT=Path(__file__).parent/'Kabita-Live-DNS-Setup-Instructions.pdf'
INK=HexColor('#263c3c');TEAL=HexColor('#125465');RUST=HexColor('#963f28');PAPER=HexColor('#f5efdf');LINE=HexColor('#d2c6ac')
styles=getSampleStyleSheet()
styles.add(ParagraphStyle(name='BodyCopy',fontName='Helvetica',fontSize=10.5,leading=15,textColor=INK,spaceAfter=7))
styles.add(ParagraphStyle(name='SectionTitle',fontName='Helvetica-Bold',fontSize=12.5,leading=17,textColor=TEAL,spaceBefore=13,spaceAfter=8))
styles.add(ParagraphStyle(name='DocTitle',fontName='Times-Roman',fontSize=28,leading=32,textColor=TEAL,spaceAfter=12))
styles.add(ParagraphStyle(name='SmallCopy',fontName='Helvetica',fontSize=9,leading=12.5,textColor=INK,spaceAfter=7))
styles.add(ParagraphStyle(name='TableCell',fontName='Helvetica',fontSize=10,leading=14,textColor=INK))
styles.add(ParagraphStyle(name='Notice',fontName='Helvetica-Bold',fontSize=10.5,leading=15,textColor=RUST))
story=[]
def p(s,style='BodyCopy'):story.append(Paragraph(s,styles[style]))
def h(s):p(s,'SectionTitle')
def bullet(s):p('&#8226; '+s)
def notice(s):
 t=Table([[Paragraph(s,styles['Notice'])]],colWidths=[483]);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),PAPER),('BOX',(0,0),(-1,-1),.5,LINE),('LEFTPADDING',(0,0),(-1,-1),12),('RIGHTPADDING',(0,0),(-1,-1),12),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8)]));story.append(t);story.append(Spacer(1,10))
def link(label,url):return f'<a href="{url}" color="#125465"><u>{label}</u></a>'
# Page 1
p('Connect the domain.<br/>Keep ownership unchanged.','DocTitle')
p('<b>kabitalive.com - GitHub Pages DNS setup</b>')
p('Prepared for the domain owner and hosting administrator<br/>From Ahimanikya Satapathy | 1 October 2026 (UTC)','SmallCopy')
notice('Please wait for our confirmation before switching website DNS. The GitHub Pages address returned 404 during the pre-cutover check; the new site must be published and tested first.')
p('The domain owner retains registration, renewal and DNS control. No domain transfer, transfer code, nameserver change or account-password sharing is required. Only the website destination will change.')
h('1. Preparation by the Kabita Live website team')
bullet('Publish and test the redesigned site at '+link('ahimanikya.github.io/kabita-live/','https://ahimanikya.github.io/kabita-live/')+'.')
bullet('Set <b>kabitalive.com</b> as the custom domain in the repository: <b>Settings &gt; Pages</b>, before changing website DNS. The repository uses GitHub Actions for publication.')
bullet('Arrange GitHub domain verification and send the domain administrator the exact TXT record name and value generated by GitHub. Do not enter a guessed or placeholder value.')
p('The administrator adds the TXT record; our team completes verification. Keep that TXT record afterwards. It authorises GitHub Pages use with our account without transferring domain registration or DNS control. [1, 2]','SmallCopy')
h('2. Open the current DNS settings and make a backup')
p('Current public records indicate Hostinger infrastructure. In Hostinger, open <b>Domains &gt; Domain portfolio &gt; Manage &gt; DNS / Nameservers</b> for <b>kabitalive.com</b>. For a domain registered elsewhere, check <b>External domains</b>. [3]')
p('Export or screenshot the complete existing DNS zone. Record any website forwarding and CDN settings. Preserve the current nameservers and keep the existing website files and hosting available throughout the transition.')
h('3. Check Hostinger CDN at the agreed switching time')
p('The current <b>www</b> record points to Hostinger CDN. If enabled, disable CDN before entering custom website records: <b>Websites &gt; Dashboard &gt; Performance &gt; CDN</b>. Active CDN management can overwrite the root and www destinations. Keep a record of the prior settings for rollback. [4]')
story.append(PageBreak())
# Page 2
p('The DNS records to enter','DocTitle')
h('4. Replace only the website records')
p('After our readiness confirmation, configure the following records in the existing DNS zone. These are GitHub Pages destinations. [1, 5]')
rows=[['Type','Name / Host','Points to / Value','TTL (seconds)'],['A','@','185.199.108.153','300'],['A','@','185.199.109.153','300'],['A','@','185.199.110.153','300'],['A','@','185.199.111.153','300'],['CNAME','www','ahimanikya.github.io','300']]
t=Table([[Paragraph(x,styles['TableCell']) for x in row] for row in rows],colWidths=[58,92,224,109],repeatRows=1)
t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),PAPER),('LINEBELOW',(0,0),(-1,0),1,TEAL),('LINEBELOW',(0,1),(-1,-1),.35,LINE),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8),('LEFTPADDING',(0,0),(-1,-1),9)]));story.append(t);story.append(Spacer(1,14))
p('<b>@</b> means the main domain, <b>kabitalive.com</b>. TTL is measured in seconds; use the provider\'s minimum permitted value if 300 is unavailable.')
bullet('Replace conflicting website destinations for <b>@</b> and <b>www</b>. Do not leave old hosting A records alongside the four new A records. Replace any conflicting root ALIAS/ANAME record as applicable.')
bullet('For this IPv4 setup, remove the old root <b>AAAA</b> records too. Otherwise, IPv6 visitors may still reach the previous host. GitHub IPv6 records can be configured separately later.')
bullet('Replace the current <b>www</b> CNAME with <b>ahimanikya.github.io</b>. Do not include <b>https://</b>, a trailing slash or <b>/kabita-live/</b>.')
bullet('Do not add wildcard records or use URL forwarding as a substitute for this DNS setup.')
h('5. Preserve email and other services')
notice('Do not reset the DNS zone or cancel the existing hosting account as part of this change. Website routing and email services must be handled separately.')
p('Leave <b>MX, SPF, DKIM and DMARC</b> records unchanged. Preserve mail-related hostnames, service-verification records and unrelated subdomains.')
p('The observed email destinations are <b>mx1.hostinger.in</b> (priority 5) and <b>mx2.hostinger.in</b> (priority 10). Preserve these records and the email subscription. We will test sending and receiving after the website switch.')
story.append(PageBreak())
# Page 3
p('Confirm the connection','DocTitle')
h('6. Coordinate verification after saving')
p('Please send us the updated website records and the time of the change. Our team will complete GitHub HTTPS setup and check the following together with you:')
bullet('<b>https://kabitalive.com</b> displays the redesigned site.')
bullet('<b>https://www.kabitalive.com</b> redirects to the main domain, with a valid HTTPS connection.')
bullet('The homepage, edition pages, poems, images and navigation load correctly.')
bullet('Domain email sends and receives normally.')
p('DNS propagation and HTTPS availability can take up to 24 hours. GitHub provisions the certificate after the DNS configuration is correct; our team will enable <b>Enforce HTTPS</b> for the custom domain when available. [1, 5]')
h('If the switch needs to be reversed')
p('Coordinate with us to restore the previous website DNS configuration from your backup, including the prior CDN settings if applicable. Use the provider\'s saved configuration rather than treating a list of CDN-resolved IP addresses as a permanent rollback target. Keep the earlier hosting available until the new site is confirmed stable.')
h('Current state recorded before the change')
p('<b>GitHub repository:</b> ahimanikya/kabita-live (public)<br/><b>Pages address:</b> https://ahimanikya.github.io/kabita-live/<br/><b>Custom domain in GitHub:</b> not yet configured at the check<br/><b>Pages HTTP check:</b> 404 - not ready for DNS cutover<br/><b>Nameservers:</b> ns1.dns-parking.com and ns2.dns-parking.com','SmallCopy')
p('These observations were checked on 1 October 2026 (UTC). Reconfirm readiness at the agreed switching time. No DNS or GitHub domain settings were changed when preparing this guide.','SmallCopy')
h('Official setup references')
refs=[('GitHub: managing a custom domain','https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site'),('GitHub: domain verification','https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages'),('Hostinger: managing DNS records','https://support.hostinger.com/en/articles/1583249-how-to-manage-dns-records-at-hostinger'),('Hostinger: CDN settings and DNS behaviour','https://www.hostinger.com/support/7935917-hostinger-cdn-website-optimization/'),('GitHub: HTTPS and DNS requirements','https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https')]
for i,(label,url) in enumerate(refs,1):p(f'[{i}] '+link(label,url),'SmallCopy')
story.append(Spacer(1,6));p('Thank you for your continued support of Kabita Live.<br/><b>Ahimanikya Satapathy</b>')
def decoration(c,doc):
 w,h=A4;c.setFillColor(PAPER);c.rect(0,h-76,w,76,fill=1,stroke=0)
 logo=ROOT/'kb/artifacts/design/brand-guide/exports/kabita-live-logo.png'
 c.drawImage(str(logo),56,h-60,width=139,height=38.2,mask='auto')
 c.setFillColor(TEAL);c.setFont('Helvetica',9);c.drawRightString(w-56,h-44,'DOMAIN CONNECTION GUIDE')
 c.setStrokeColor(LINE);c.setLineWidth(.5);c.line(56,44,w-56,44)
 c.setFillColor(INK);c.setFont('Helvetica',8);c.drawString(56,30,'Kabita Live | Domain ownership remains unchanged');c.drawRightString(w-56,30,f'{doc.page} / 3')
doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=56,leftMargin=56,topMargin=96,bottomMargin=60,title='Kabita Live - DNS Setup Instructions',author='Ahimanikya Satapathy')
doc.build(story,onFirstPage=decoration,onLaterPages=decoration)
r=PdfReader(OUT);assert len(r.pages)==3,len(r.pages)
t='\n'.join(p.extract_text() for p in r.pages)
for x in ['185.199.108.153','185.199.109.153','185.199.110.153','185.199.111.153','ahimanikya.github.io','mx1.hostinger.in','404'] :assert x in t,x
print(OUT);print('3 pages; DNS and readiness text checks pass')
