from save_writer import save,source
save(318,dict(
 paragraphs=['Ranu Uniyal writes poetry in English and Hindi and teaches English at the University of Lucknow. She completed her doctorate at the University of Hull; her academic interests include women’s writing, disability studies and poetry. Her collections include Across the Divide, December Poems, The Day We Went Strawberry Picking in Scarborough and Saeeda Ke Ghar.', 'Her Kabita Live poems bring landscape close to the senses while questioning how people inhabit it. “Plums versus Pullum” begins with the taste and local name of fruit, recalling Ranikhet, Almora and a mother’s kitchen. “At Kedarnath” turns to the force of a flood, using the imagery of Shiva and a river’s voice to challenge human disregard for the natural world.'],
 books=[dict(title='The Day We Went Strawberry Picking in Scarborough',detail='English poetry; Dhauli Books, 2018. Listed in the author’s university bibliography.',url='https://udrc.lkouniv.ac.in/Content/FacultyCV/CV_134.pdf#page=3'),dict(title='Saeeda Ke Ghar',detail='Hindi poetry; Rashmi Prakashan, 2021. Review in Rhetorica Quarterly.',url='https://www.lkouniv.ac.in/site/writereaddata/siteContent/202206091043553258Rhetorica_Vol_II_Issue_III_1.pdf')],
 sources=[source('Ranu Uniyal — author biography','https://ranuuniyal.com/about/','English/Hindi poet, Lucknow/Hull academic background, research interests and four named poetry books.'),source('University of Lucknow — Ranu Uniyal Pant CV','https://udrc.lkouniv.ac.in/Content/FacultyCV/CV_134.pdf','Opened university CV, pages 1–4: institution, qualifications, specializations and dated book bibliography.'),source('Rhetorica Quarterly — Saeeda Ke Ghar review','https://www.lkouniv.ac.in/site/writereaddata/siteContent/202206091043553258Rhetorica_Vol_II_Issue_III_1.pdf','Indexed printed page 82 names Ranu Uniyal, publisher Rashmi Prakashan, 2021, Hindi and ISBN 9789391326050.','search_index')],
 identity_match='University, bilingual poetry, two originally captured book titles and author website agree; institutional CV uses fuller name Ranu Uniyal Pant.',
 poems_read=[dict(id=635,title='At Kedarnath',coverage='Complete original, all three stanzas',basis='Flood, temple/Shiva/Nandi, personified river and final challenge to human treatment of nature.'),dict(id=390,title='Plums versus Pullum',coverage='Complete captured text including second block beginning When People stop listening',basis='Fruit name, taste, mother’s kitchen and stains; second block moves into flowers, ashes, silence and withheld grief.')],
 limitations=['Author website contains two/four counts, placeholder text, malformed book links and unrelated Devrani Jethani prose under Saeeda Ke Ghar. University bibliography/review used for titles instead.','Spanish translation dates differ between author and institutional records; omitted from new narrative.','Second block of 390 may be a separately titled poem; source left intact and not silently reclassified.','At Kedarnath discussed as poetic representation, not verified disaster chronology or river geography.'],
 research_leads=[dict(url='https://ranuuniyal.com/saeeda-ke-ghar-book/',finding='Opened; incorrect unrelated book review mixed with Saeeda excerpts. Not suitable as selected book link.')],next_action='Author/editor review; clarify poem 390’s embedded title boundary without altering capture.'
))
