from save_writer import save,source
save(293,dict(
 paragraphs=['Rita Chugh writes poetry in Hindi and English. Her work appears in international literary magazines and anthologies, and POP-Star Poetry lists her among its volunteer editors and publishers. Alongside poems of personal feeling, her published writing reflects on poetry itself as a way to shape and share emotion.', '“ज़िन्दगी का फ़लसफ़ा” returns to a refrain of not understanding, placing love, disappointment and unspoken wishes beside one another. “Passion For Poetry” offers a more assured voice: writing becomes a source of rhythm and delight. Read together, the poems move between uncertainty about life and trust in expression.'],
 sources=[source('POP-Star Poetry — publishing team','https://www.popstarpoetry.com/team-3','Opened team page identifies Rita Chugh as volunteer administrator/editor/publisher.'),source('POP-Star Poetry — Poetry is Painting That Speaks','https://www.popstarpoetry.com/post/poetry-is-painting-that-speaks','Indexed original poem and contributor bio corroborate bilingual poet, editor and anthology contributor; direct open cache miss.','search_index'),source('Inner Child Press — W.A.R. II','https://www.innerchildpress.com/resources/WAR%20II%20GRATIS.pdf','Indexed publisher anthology contents list Rita Chugh (India), p59; supports anthology contribution.','search_index')],
 identity_match='Distinctive bilingual writing/editorial profile and Hindi/English publication pattern in captured biography agree with journal bio and team listing. Publisher anthology confirms same named India-based contributor.',
 poems_read=[dict(id=315,title='ज़िन्दगी का फ़लसफ़ा',coverage='Complete original, all five stanzas',basis='Repeated कुछ समझ नहीं आता, joy/grief, concealed longing, competing paths.'),dict(id=312,title='Passion For Poetry',coverage='Complete original, all four stanzas including capture artefact at start',basis='Writing as devotion and pleasure; weaving and pearls metaphors, rhyme and musical expression.')],
 limitations=['World-record, ambassador, icon, honorary titles and broad award claims not verified with awarding organizations; omitted from enrichment. Original biography preserved.','Anthology totals change by date; no total asserted.','No verified publisher link for the named Hindi books Bhor Ki Bhaasha or Aakaash Khyalon Ka; omitted from selected books.','312 has a leading p> capture artefact and is supplementary rather than contents-listed; source and assignment untouched.'],
 research_leads=[dict(url='https://professionalwomantld.webador.com/1374391_rita-chugh',finding='Indexed 2023 profile names Bhor Ki Bhaasha and Aakaash Khyalon Ka; no independent publisher/ISBN record found in this pass.')],next_action='Editor/author to verify bibliography and source artefact; independent factual review of new narrative.'
))
