from save_writer import save,source
save(270,dict(
 paragraphs=['Raja Rajeswari Seetha Raman is a Malaysian poet, translator and literary critic whose work connects Malay literature with readers across languages. Her collections include Mekar Bunga. In her account of the 2025 Toshali Literature Festival in Odisha, she describes the launch of Metamorfosis, her Malay translation of poems by Pradeep Biswal, alongside an Odia translation of her own poetry by Pragyan Prabartika Dash.', '“Embrace Solitude in Grace” treats time alone as a source of imagination and renewed purpose. Its repeated invitations build into a catalogue of what solitude may hold: books, colour, love, ideas and words. The poem’s encouraging voice presents inward attention as a way to return to life with greater openness.'],
 books=[dict(title='Metamorfosis',detail='Poems by Pradeep Biswal, translated into Malay by Raja Rajeswari Seetha Raman; Shalandi, launched in 2025. Linked author’s publication account.',url='https://dewansastera.jendeladbp.my/2025/02/13/15843/')],
 sources=[source('Dewan Sastera — Raja Rajeswari Seetha Raman on Toshali 2025','https://dewansastera.jendeladbp.my/2025/02/13/15843/','Opened first-person account dated 13 February 2025, Malay/Odia translation exchange, Metamorfosis authorship/translation and Shalandi publisher; full relevant paragraphs read.'),source('Toshali Literature Festival — 2025 programme','https://toshalilitfest.in/2025/schedule.php','Indexed organizer programme identifies Malaysian poet, guest of honour and chair of English poetry session; direct open cache miss.','search_index'),source('Indonesian education repository — Yogya dalam Nafasku anthology contributor biography','https://repositori.kemendikdasmen.go.id/34800/1/ANTOLOGI%20PUISI%20oke.pdf','Indexed printed p362 identifies Malaysian poet/translator, Mekar Bunga, Malay literary criticism and translation work; direct PDF timeout.','search_index')],
 identity_match='Exact full name, Malaysia, poetry/translation and documentary dates in Dewan Sastera biography agree with captured profile. Author’s account and organizer schedule independently connect her to Toshali; no reliance on similarly named Indian entities.',
 poems_read=[dict(id=259,title='EMBRACE SOLITUDE IN GRACE',coverage='Complete original, all six stanzas',basis='Repeated embrace/in solitude invitations, art/book/idea catalogue, change and spiritual closing.')],
 limitations=['Award and translation-language totals vary with date; neither totals nor unverified honorary titles included.','Book link is the translator’s publication account, explicitly labelled, not a retail page.','No current teaching appointment, precise degree institution or inferred personal faith asserted.','Mekar Bunga catalogued in library search results and anthology; individual stable catalogue link not resolved.'],
 research_leads=[dict(url='https://www.w-ilmu.intan.my/neuseal/Record/0000009523/Similar',finding='Indexed related-book list records Mekar Bunga (2006) by exact full name; direct open failed. Seek dedicated record for future book link.'),dict(url='https://www.utusan.com.my/terkini/2025/07/dr-raja-rajeswari-kagum-nilai-estetika-sastera-melayu/',finding='Indexed 2025 interview names Wind of Hope and Malay translation work. Extra book metadata not imported without dedicated record.')],next_action='Independent editor/author review and fuller bibliography; retain translator and Odia translator credits.'
))
