from save_writer import save,source
works=[(789,'Five Haiku','All five opening haiku and the five-poem Floating World sequence','Pond life, bodily perspective, lake animals and human intrusion.'),(739,'Hold On','All five haiku','Moss, slug, snail, sparrow remains and moonlight.'),(640,'Five haiku','All five haiku','Cowhand, apples, snow tracks, cherry blossoms and cicada shell.'),(633,'River Rocks','All five haiku','Kayak movement, owl, storm, social distance and quarter moon.'),(527,'A haiku sequence: five individual haiku','All ten short poems, including separately headed five haiku or senryu','Crop cycle and human/family scenes; juxtaposition and humour.'),(420,'Speaker’s Corner','All four haiku','London weather, shared umbrella, crow and rain dispersing tourists.')]
save(341,dict(
 paragraphs=['Randy Brooks is a haiku and tanka poet, editor and teacher associated with Millikin University in Illinois. With Shirley Brooks, he publishes Brooks Books and co-edits Mayfly, a magazine of English-language haiku. His books include Walking the Fence: Selected Tanka and The Art of Reading and Writing Haiku, which brings student poems and readers’ responses into conversation.', 'His Kabita Live sequences find humour and tenderness in precise encounters: a shared umbrella, apples labelled for friends, a kayak touching river rock. In “Hold On” and “Floating World”, moss, small animals and the body’s changing viewpoint invite close attention. The brief poems leave space for readers to make connections without explaining each image.'],
 books=[dict(title='Walking the Fence: Selected Tanka',detail='Brooks Books, 2019. ISBN 9781929820184.',url='https://www.brooksbookshaiku.com/Brooks-Tanka.html'),dict(title='The Art of Reading and Writing Haiku: A Reader Response Approach',detail='Brooks Books, 2019. ISBN 9781929820177.',url='https://www.brooksbookshaiku.com/Brooks-ArtReadWriteHaiku.html')],
 sources=[source('Millikin University — Randy Brooks','https://millikin.edu/about/administration/faculty-staff-directory/randy-brooks','Institutional biography confirms teaching, former dean role, publishing with Shirley Brooks and Mayfly.'),source('Brooks Books — Walking the Fence','https://www.brooksbookshaiku.com/Brooks-Tanka.html','Author/publisher book page verifies title, tanka form, year and ISBN.'),source('Brooks Books — The Art of Reading and Writing Haiku','https://www.brooksbookshaiku.com/Brooks-ArtReadWriteHaiku.html','Author/publisher page confirms book and use of students’ haiku and reading responses.'),source('Brooks Books','https://www.brooksbookshaiku.com/','Current publisher page identifies Randy and Shirley, Mayfly and book list.')],
 identity_match='Exact Millikin institution, Shirley Brooks collaboration, Mayfly editorship and two book titles agree with captured profile.',
 poems_read=[dict(id=i,title=t,coverage=c,basis=b) for i,t,c,b in works],
 limitations=['Institutional page labels adjunct and describes past dean role; capture says emeritus. New narrative uses associated with Millikin rather than resolving administrative labels.','527 and 789 contain more short poems than their top-level titles imply; every embedded sequence read and source retained.','Family and bodily images are literary observations, not additional private biographical claims.'],research_leads=[],next_action='Independent author/editor review of narrative and selected bibliography.'
))
