from save_writer import save,source
save(342,dict(
 paragraphs=['Reema Sinha is a Lucknow writer and the founder of Niharika Sahitya Manch, a forum for literary and cultural gatherings. Her contributions to Kabita Live appear in Hindi and English, bringing together devotional address and attentiveness to another person’s feelings.', 'In “भक्तिन के नयनों में अमर प्रेम रहने दो”, flowers, sandalwood and prayer frame love as a sustained act of devotion. “That old woman” turns instead to an encounter in moonlight: the observer senses grief and remembered joy but cannot fully understand them. Both poems approach feeling through what can be seen, offered or left unsaid.'],
 sources=[source('Sahitya Rachana — रीमा सिन्हा','https://www.sahityarachana.com/2021/01/hindi-kavita-roti-kapada-aur-makaan-reema-sinha.html','Published Hindi poetry and Lucknow byline; page read during research-055.'),source('Samar Saleel — Niharika Sahitya Manch gathering, April 2025','https://samarsaleel.com/under-the-auspices-of-niharika-sahitya-manch-country-of-india-foundation-trust/464895','Report dated 22 April 2025 identifies founder Dr Reema Sinha and literary/cultural gatherings in Lucknow.')],
 identity_match='Captured Lucknow location and founder role at named Niharika Sahitya Manch match report; journal confirms Hindi name and city. Potential duplicate Rima Sinha 410 retained separately; no works reassigned.',
 poems_read=[dict(id=489,title='भक्तिन के नयनों में अमर प्रेम रहने दो',coverage='Complete original, all three stanzas',basis='Devotee refrain, flower/sandalwood imagery, waiting and prayer.'),dict(id=414,title='That old woman',coverage='Complete original, all six stanzas',basis='Moonlit observation, tears and smile, empathy without full understanding.')],
 limitations=['Possible duplicate with 410 Rima Sinha requires editor confirmation; counts remain profile records, not deduplicated people.','No publisher records established for Asha and Noyonika; no book links added.','Degree, current press-office roles and honorary award claims in capture not independently verified and not repeated in new narrative.','No inference of author’s personal religious identity from a devotional speaker.'],
 research_leads=[dict(url='https://www.youtube.com/watch?v=lLcrl2PuKWo',finding='Interview description indexed previously names Lucknow, Niharika and books; direct open failed, audio not auditioned. Retain as future bibliography lead.')],next_action='Confirm preferred name and duplication with 410; author/editor to supply publisher links for Asha and Noyonika.'
))
