from save_writer import save,source
save(411,dict(paragraphs=[
"Mahima Gantayat writes poetry and short fiction from Rayagada, Odisha, working in Hindi and English. Her first Hindi poetry collection, An Kahi Baaten, was published by Aditya Bharat in 2026. Speaking at its launch, she described the books in her home and school libraries, along with her family’s literary tradition, as early encouragements to write.",
"Her English poems in Kabita Live approach memory through familiar places and the ache of absence. In ‘Roots of Childhood’, a tree holds the memory of siblings at play even as adulthood carries them towards responsibilities and new friendships. ‘Echoes of You?’ turns towards the silence left by a once-attentive listener, asking whether the words shared between two people can continue to reach across their distance."],
sources=[source('Odishabarta — launch of An Kahi Baaten','https://odishabarta.com/young-writer-mahima-gantayats-first-hindi-poetry-collection-an-kahi-baaten-launched/',['4 July 2026 launch; Aditya Bharat Cuttack; first Hindi collection; author’s comments on libraries and literary family']),source('Mahima Gantayat — public author profile','https://in.linkedin.com/in/mahima-gantayat-520316397',['Rayagada; Kendriya Vidyalaya; first-book post titled अनकही बातें'],'search_index_excerpt')],
identity_match='Uncommon full name, Rayagada location and Hindi/English writing match captured contributor; author-profile first-book post independently agrees with launch report.',
poems_read=[dict(id=591,title='Roots of Childhood',basis='Full original read: childhood tree, siblings, adult responsibilities, wind/water memory and changed friendships.'),dict(id=585,title='Echoes of You?',basis='Full original read, including appended If radio could speak verses: missing listener and memory, then a marked shift to radio/grief/victory/injustice. Narrative uses only clearly titled opening movement.')],
limitations=['School stage in 2025 biography not asserted as current; unverified Proficient Writer award omitted.','Poem 585 contains an apparent second title and radio passage; preserved unchanged and flagged for editorial separation review, not attributed to a different writer.','Launch report is dated July 2026; no stable retail product link verified, so collection mentioned in prose without a purchase card.','LinkedIn accessed through search index, not claimed as direct-open evidence.'],
next_action='Independent author/editor review; confirm whether poem 585 includes a second work and verify book metadata from its title page.'))
