from save_writer import save,source
save(444,dict(paragraphs=[
"Meenakshi Mohan is a Maryland-based poet, educator, painter and children’s writer. Her literary work brings together an interest in visual art, learning and the lives of families. Her books include the poetry collection Symphonies of Life and the children’s books The Gift and The Rainbow in My Room. Matwaala’s author profile also records her editorial work with Inquiry in Education and Confluence.",
"In Kabita Live’s ‘Waiting’, evening becomes a landscape of prayer: saffron light, trees imagined as monks, and the distant sound of a conch lead towards a small light in a window. The closing images of a mother and a wife give the quiet scene its human centre. The poem allows hope and uncertainty to remain together, without resolving the wait."],
sources=[source('Matwaala — Meenakshi Mohan','https://www.matwaala.com/meenakshi-mohan.html',['Maryland; educator, painter, poet and children’s writer; named books; journal editorial roles']),source('Penprints — Symphonies of Life','https://penprints.in/shop/product/symphonies-of-life-by-meenakshi-mohan/',['Poetry collection by Meenakshi Mohan; Penprints, 2024'])],
books=[dict(title='Symphonies of Life',detail='Poetry · Penprints, 2024',url='https://penprints.in/shop/product/symphonies-of-life-by-meenakshi-mohan/')],
identity_match='USA location, academic/painting/children’s writing practice, both editorial affiliations and exact book title match captured biography; not the unrelated actress or nursing researcher.',
poems_read=[dict(id=718,title='Waiting',basis='Full English original read: evening, gerua, monk-like trees, returning animals, shankhnad, window light, mother’s prayer and wife’s waiting.')],
limitations=['Awards and newly reported organizational appointment omitted; editorial affiliations attributed to the festival profile rather than independently verified as current employment.','Poem’s family figures not treated as autobiographical facts.'],next_action='Independent author/editor review of narrative and current editorial affiliations.'))
