from save_writer import save,source
save(440,dict(paragraphs=[
"Manas Bakshi is a Kolkata-based English-language poet whose writing also extends to the economic history of rural Bengal. His doctorate at the University of Calcutta examined the transition from feudalism to capitalism, and his academic books explore agrarian change and land reform. His poetry collections include In the Age of Living Death, The Midnight Star and Soliloquy of a Sailor.",
"His Kabita Live poem ‘Tacitly So’ starts with marks on graph paper and follows what those marks cannot fully preserve. Bricks lose a mason’s fingerprints, discarded letters lose the trace of a postman, and felled trees can no longer invite rain. These ordinary remains turn into a meditation on forgotten labour, ecological loss and the way time erases evidence of a life."],
sources=[source('Creative Flight — Manas Bakshi’s literary and academic profile','https://www.creativeflight.in/2023/05/manas-bakshi-poet-creative-flight.html',['Kolkata; Calcutta doctorate and thesis subject; agrarian books; named poetry collections and publishers'])],
identity_match='Doctorate in rural economics plus overlapping publishers Rupa, Firma KLM, Cambridge India, Authors Press and Poetry Society of India bridge captured contributor and journal CV.',
poems_read=[dict(id=712,title='Tacitly So',basis='Full English original read: graph-paper witness, bricks and mason, dead-letter office/postman, felled oaks, impermanence and abandoned time.')],
limitations=['CV introduction says twelve books but list contains thirteen; captured biography says fifteen. Total omitted rather than treated as contradiction requiring a guessed update.','No verified individual publisher product page found; no shopping card added.','Public CV’s precise residential address and telephone not copied.'],
research_leads=[dict(query='"Manas Bakshi" site:authorspressbooks.com',finding='No usable publisher product result returned; journal bibliography used for titles only.')],next_action='Independent author/editor bibliography and narrative review.'))
