"""Research006: supported biography and contribution-based literary introductions."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[5];SITE=ROOT/'projects/site';HOME=ROOT/'kb/research/writers';DATE='2026-10-01'
def source(label,url,supports,access='opened_page'):
 return dict(label=label,url=url,supports=supports,access=access,accessed_on=DATE)
entries={
260:{'paragraphs':[
'Aparna Pradhan writes in Hindi and English and also works as an artist. Trained in zoology, she contributes poetry and articles to literary publications; her essay on Awadhi cuisine appeared in the Journal of Asian Arts, Culture and Literature. Literary Warriors Group records the launch of her books नारी अस्मिता and त्रिआयामी at its 2023 New Delhi festival.',
'Her Kabita Live poems bring questions of dignity and belonging into direct speech. छुअन asks the reader to recognise a woman’s inward life beyond her body. आख़िर क्यूँ – परायेपन का दंश follows a woman from her childhood home to marriage, asking why neither place grants her an unquestioned sense of belonging.'
], 'books':[{'title':'नारी अस्मिता','detail':'Book launch · Literary Warriors Group, 2023','url':'https://literarywarriorsgroup.wordpress.com/lwg-literary-festivals/litfest-1-0/'}],
'sources':[source('JAACL · The Delicate Flavors of Awadhi Cuisine','https://alsphere.org/wp-content/uploads/2023/09/The-Delicate-Flavors-of-Awadhi-Cuisine-by-Dr.-Aparna-Pradhan.pdf',['Article, artist and bilingual writer; zoology doctorate corroborates journal identity'],'opened_pdf'),source('Literary Warriors Group · LitFest1.0,2023','https://literarywarriorsgroup.wordpress.com/lwg-literary-festivals/litfest-1-0/',['Named book launches and poetry participation'])],
'identity_match':'Exact name, zoology doctorate, bilingual writing and visual art match the journal biography. Nepal-language namesake and student records excluded.', 'poems_read':[660,248],
'limitations':['Captured Hindi book names are encoding-damaged; preserved verbatim in source record. New titles come from organizer record rather than reconstruction.','No total collection count or award catalogue claimed; book-launch link is an event record, not a purchase destination.','Poetic speakers and injustice described in poems are not asserted to be personal biography.'], 'next_action':'Verify publisher records and original Hindi titles with editor; independent factual review pending.'},
253:{'paragraphs':[
'Aparna Mohanty is an Odia poet, translator and critic associated with Kendrapara. Her collection ଝିଅପାଇଁ ଝର୍କାଟିଏ received the Odisha Sahitya Akademi Award for 2007. Alongside her poetry, her literary work includes translation, criticism and a career teaching Odia; festival records recognise her sustained attention to women’s experience.',
'In Kabita Live’s ଦାରୁଣ ଅସହାୟତା, memories of the freedom struggle become a question addressed to the present. The poem contrasts sacrifice and the hope of human dignity with the language of ceremonial remembrance. Its repeated question about the meaning of a country gives the closing sense of helplessness its force.'
], 'books':[{'title':'ଝିଅପାଇଁ ଝର୍କାଟିଏ','detail':'Odia poetry · Orissa Book Store','url':'https://www.odishanticstore.com/product/jhiapain-jharkatia-by-aparna-mohanty'}],
'sources':[source('Institute of Knowledge Societies ·2021 panelists','https://www.iks.org.in/panelists-2021',['Poet, translator, critic, literary teaching and feminist writing']),source('Odisha Review · December2022, p.79 onward','https://magazines.odisha.gov.in/Orissareview/2022/Dec/engpdf/OR_DEC-2022.pdf',['Kendrapara identity, historical teaching career and2007 award for named collection'],'indexed_pdf_text_direct_open_failed'),source('The New Indian Express · Akademi award announcement','https://www.newindianexpress.com/states/odisha/2011/may/12/orissa-sahitya-akademi-awardees-announced-252477.html',['Poetry award for2007 announced later'],'indexed_news_text'),source('Odishantic Store · ଝିଅପାଇଁ ଝର୍କାଟିଏ','https://www.odishanticstore.com/product/jhiapain-jharkatia-by-aparna-mohanty',['Book title, author, poetry genre and publisher'])],
'identity_match':'Odia writing, Kendrapara location and state Akademi poetry award match captured biography, corroborated by government literary review and festival record.', 'poems_read':[241],
'limitations':['Award is for2007; announcement occurred later. No claim that ceremony took place in2007.','Award-organizer endpoint and full Odisha Review PDF failed direct retrieval; indexed government text and news corroboration retained.','Historical academic role not presented as a current appointment. Bibliographic romanizations vary; native title follows opened retailer record.'], 'next_action':'Author/editor review; seek accessible award-organizer archive and publisher bibliography.'},
243:{'paragraphs':[
'Aarti Mittal, also known as Rita Jain, writes poetry in English and Hindi. Her Kabita Live contributor note places her in Mumbai and describes her work with children’s skits. Her poem A Woman appeared in Our Poetry Corner, where the byline Aarti Mittal and the signature Rita connect the names she uses in her writing.',
'Her Kabita Live contributions range from the flowing-water metaphor of REFLECTIONS to the unsettling enclosed space of Hello. Fearless warrior uses the imagined voice of a child to confront the absence of safety among the living. Across these poems, changes in image and voice make room for both resilience and protest.'
], 'sources':[source('Wonderful Women of Excellence · Aarti Mittal personal account','https://anyflip.com/stpj/lxqs/basic',['Explicit Rita Jain/Aarti Mittal name connection'],'indexed_book_text_direct_open_failed'),source('Our Poetry Corner · A Woman','https://ourpoetrycorner.wordpress.com/2016/02/11/a-womanby-aarti-mittal/',['Published poem by Aarti Mittal signed Rita'],'indexed_poem_text_direct_open_failed')],
'identity_match':'Distinctive alias Rita Jain explicitly matched in first-person anthology entry, independently linked to Aarti/Rita poem byline and signature. Mumbai/skit details remain attributed to journal note.', 'poems_read':[360,345,229],
'limitations':['Direct retrieval of anthology and poem page failed; indexed text was readable. No unsupported current school employment or individual book inferred.','Child speaker and abuse imagery are literary material, not biographical allegations or personal experiences assigned to the author.','Excluded unrelated medical, acting and business namesakes. Personal family details in anthology intentionally omitted.'], 'next_action':'Verify author bibliography and current professional description through a primary author or school source.'},
240:{'status':'source_limited_local_draft','paragraphs':[
'Anita Ray’s ନିଜକୁ ଖୋଜିବାକୁ ପଡ଼େ appears in Kabita Live’s June 2023 edition. The poem follows a speaker searching for a self among familiar people, shifting expectations and the demands of an inward life.',
'A leaf scorched by dry heat waits for rain, while silence carries the memory of closeness. These images give physical shape to uncertainty and longing. The poem moves towards an unresolved ache rather than an easy answer, keeping the search in its title open.'
], 'sources':[], 'identity_match':'Local writer240 and poem216 established. Empty biography leaves no independent place, work or professional anchor for same-name external literary records.', 'poems_read':[216],
'leads':[source('Odisha Sambad · ତମେ କେମିତିକା ଜହ୍ନ review','https://odishasambad.in/nook-notice-tume-kemitika-jahna-poetry-collection-by-anita-ray/',['Same-name Odia poet and Athena Books collection; not confidently linked to writer240'],'indexed_review_text_direct_open_failed')],
'limitations':['No unverified book, award, birthplace or employment attached. Native spelling in external review is not silently applied to captured English-only name.','Name and writing language alone are insufficient to establish identity; English-language namesake collection also excluded.'], 'next_action':'Obtain contributor biography or a matching poem/publication identifier before linking external bibliography.'},
206:{'paragraphs':[
'Asish Kumar Mishra writes in Odia and is associated with Subarnapur. His literary work also appears on StoryMirror under the name Ashish Kumarmishra, where a signed contribution identifies the same district. Kabita Live introduces him through the poem ଦୁଃଖ.',
'The flower and the bee give this poem its recurring image of trust and hurt. Petals, fragrance and wind hold the feeling in the natural world before the final stanza turns directly towards another person. Sorrow becomes a paradox: something endured, yet also something the speaker fears losing.'
], 'sources':[source('StoryMirror · ସ୍ୱପ୍ନ, Ashish Kumarmishra','https://storymirror.com/read/oriya/story/s-pn/4e6prmlp',['Signed Odia contribution with exact native name and Subarnapur district'])],
'identity_match':'Exact native full name ଆଶିଷ କୁମାର ମିଶ୍ର, Odia writing and Subarnapur district corroborate journal biography; transliteration variant recorded. No employment or award match inferred.', 'poems_read':[190],
'limitations':['External evidence is an author-posted literary contribution, not independent institutional certification; identity confidence rests on full native name, language and district.','No awards, books, age or current address inferred. Public phone and village-level address omitted.','Poem interpretation does not assert private relationship history.'], 'next_action':'Author/editor identity confirmation and any verified collection record would strengthen the profile.'}
}
if __name__=='__main__':
 profiles={p['id']:p for p in json.loads((SITE/'data/writer-profiles.json').read_text())}
 for ident,item in entries.items():
  current=json.loads((SITE/'data/writer-enrichment.json').read_text())
  if str(ident) in current:raise RuntimeError(f'Refuse overwrite {ident}')
  reader={'sections':[{'heading':'Life and writing.','language':'en','paragraphs':item['paragraphs']}],'books':item.get('books',[]),'sources':[{k:s[k] for k in ['label','url']} for s in item['sources']],'reviewed_on':DATE}
  record={'writer_id':ident,'name':profiles[ident]['name'],'reviewed_on':DATE,'batch':'research-006','status':item.get('status','source_checked_local_draft'),'independent':False,'portrait_action':'unchanged','reader_draft':reader,**{k:v for k,v in item.items() if k not in ['paragraphs','books','status']}}
  record['limitations'].append('Same-assistant research/interpretation; author/editor factual review pending.')
  (HOME/'enrichment'/f'{ident}.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n');current[str(ident)]=reader;(SITE/'data/writer-enrichment.json').write_text(json.dumps(current,ensure_ascii=False,indent=2)+'\n');print('Saved writer',ident)
