"""Save five researched profile drafts without altering source biographies or poems."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[5];SITE=ROOT/'projects/site';HOME=ROOT/'kb/research/writers';DATE='2026-10-01'
def source(label,url,supports,access='opened_page'):
 return dict(label=label,url=url,supports=supports,access=access,accessed_on=DATE)
entries={
321:{'status':'source_limited_local_draft','paragraphs':[
'Ashish Vidyarthi contributes Hindi poetry to Kabita Live. His poem जिंदगी जिंदादिली का नाम है appears in the April 2024 edition and centres on a small, everyday gesture: a smile offered in the midst of difficulty.',
'The poem imagines happiness flowering from the mud of sorrow. Short stanzas move from the inward life to encounters with others, returning at the close to the opening encouragement to smile. Its direct address gives the verse the warmth of spoken reassurance.'
], 'sources':[], 'identity_match':'Journal writer321 and poem392 establish the contribution. No independently matching biography found; name alone cannot establish identity with the actor.', 'poems_read':[392],
'limitations':['Exact-name, Hindi-title and name-plus-poetry searches did not establish an external identity. No acting career, awards, location or collections inferred.','Contribution-based introduction only; journal phrase wellknown is not amplified as an independently established claim.'], 'next_action':'Seek a contributor biography or a verified author link matching this poem.'},
292:{'paragraphs':[
'Anju Kapoor is a Bahrain-based poet and visual artist who writes in English and Hindi. The Cultural Reverence published her illustrated poem HER in June 2024, crediting both the verse and the painting to her. Her writing brings the inward life into conversation with images drawn from the natural world.',
'In Kabita Live’s A Circle - Its Bearing on my Life, the circle expands from the beginnings of life to time, feeling and uncertainty. A butterfly, roots and fruit, and pearls gathered into a necklace carry the poem through successive transformations. The recurring definition of the circle gives these changing images a shared centre.'
], 'sources':[source('The Cultural Reverence · HER','https://theculturalreverence.wordpress.com/2024/06/07/her-an-illustrated-poem-by-anju-kapoor-bahrain/',['Bahrain identity; poem and painting by same contributor, June2024']),source('PTSD anthology · contributor note','https://www.ptsd-thebook.com/whats-inside',['Bilingual writer, Bahrain and University of Mumbai banking/finance study matching journal biography'])],
'identity_match':'Exact name, Bahrain, bilingual writing and distinctive University of Mumbai banking/finance credential match captured biography; literary journal additionally establishes visual-art practice.', 'poems_read':[313],
'limitations':['No health diagnosis inferred from anthology participation or first-person poetry. Residence-duration numbers vary by publication date and are omitted.','Nature imagery statement is literary interpretation of HER and the local poem, not a claim about all work.'], 'next_action':'Author/editor factual review; seek any individual collection record when available.'},
286:{'paragraphs':[
'Ashok Bhargava is a Vancouver-based poet and photographer who writes in English and Hindi. His collections include Skipping Stones, Mirror of Dreams, A Kernel of Truth and Lost in the Morning Calm. His author website brings his poetry and photography together with records of literary community activity.',
'Kabita Live’s Maya - Illusion uses very short stanzas to unsettle the certainty of knowing. The speaker moves from I and you to we and they, repeatedly handing knowledge from one side to the other. Its final turn towards illusion makes the spare pattern into a meditation on perception.'
], 'books':[{'title':'Skipping Stones','detail':'Poetry · Virgo Publishers, 2002','url':'https://ashokbhargava.wordpress.com/publications/'},{'title':'Lost in the Morning Calm','detail':'Poetry · Sihanul Publishers, 2009','url':'https://ashokbhargava.wordpress.com/publications/'}],
'sources':[source('Ashok K. Bhargava · About','https://ashokbhargava.wordpress.com/about/',['Vancouver; English and Hindi writing; photographer']),source('Ashok K. Bhargava · Publications','https://ashokbhargava.wordpress.com/publications/',['Four named poetry collections, publisher and year details']),source('Ashok K. Bhargava · author website','https://ashokbhargava.wordpress.com/',['Dated literary community activity'],'indexed_page_text')],
'identity_match':'Captured display spelling Bhargab is preserved. The supplied biography explicitly names Ashok Bhargava, a bilingual Canadian poet, matching the author website; do not merge with same-name US obituary.', 'poems_read':[296],
'limitations':['Reader narrative uses the author’s published spelling Bhargava; canonical captured name remains unchanged pending editorial correction.','No seven-book total or unverified awards included. Historical website events are not framed as current appointments.'], 'next_action':'Ask editor to reconcile captured surname spelling during factual review.'},
285:{'paragraphs':[
'Alka Nigam is a Lucknow-based Hindi writer associated with Lafzon Ki Potli. Her signed poetry on YourQuote carries both that name and the city, while the first issue of Brahmand: Voice of the Cosmos also identifies her as a contributor. Her work includes poetry and prose.',
'In Kabita Live’s छिन्नमस्तिका, an insistent address draws on Sita, Panchali, Gargi and goddess imagery. The poem moves from flowers and adornment to resolve and confrontation, ending with the fierce form named in its title. Its repeated commands and closing refrain give the piece an emphatic spoken rhythm.'
], 'sources':[source('YourQuote · Alka Nigam, signed poem','https://www.yourquote.in/alka-nigam-4nii/quotes/usne-puuchaa-prem-kyaa-hai-o-mtvaalii-aur-mainne-hns-kr-aage-crv082',['Name, Lucknow and Lafzon Ki Potli match journal biography']),source('Brahmand: Voice of the Cosmos · Volume1 Issue1','https://neelamsaxenachandra.com/wp-content/uploads/2021/10/ISSUE-1.pdf',['Signed Hindi prose contribution with Lucknow/Lafzon Ki Potli affiliation'],'indexed_pdf_text_direct_open_failed')],
'identity_match':'Name, exact literary-page name and city appear together in the signed YourQuote entry and magazine PDF, matching the journal note.', 'poems_read':[301],
'limitations':['Vama collection subtitle, publication year and Uttar Pradesh Hindi Sansthan grant are supplied-journal claims not independently corroborated; not repeated in enrichment.','PDF indexed contribution was readable; direct PDF retrieval failed.','Description of religious and gendered imagery is literary interpretation, not endorsement or inference about private beliefs.'], 'next_action':'Find publisher catalogue or Hindi Sansthan grant record before expanding book and award details.'},
275:{'paragraphs':[
'Avantika Vijay Singh is a writer, editor, poet and photographer. Her poetry books include Flowing… in the river of life and Dancing Motes of Starlight. She also writes Ordinary People, Extraordinary Lives for the Times of India, bringing everyday experience into a different, often humorous register.',
'Her Kabita Live poem Amaltas… begins with the yellow flowers of summer and opens into a remembered landscape from the Ramayana. The flowering tree connects a present moment of looking with Ram’s journey towards Sugriv and the hills of Rishyamukha. Nature becomes a meeting place for observation and story.'
], 'sources':[source('Setu · Avantika Vijay Singh, March2025','https://www.setumag.com/2025/03/poetry-avantika-vijay-singh.html',['Author identity, writing/editing/photography, two named poetry books']),source('Times of India · Ordinary People, Extraordinary Lives','https://timesofindia.indiatimes.com/blogs/ordinary-people-extraordinary-lives/',['Named author and blog, everyday subjects and humorous essays'])],
'identity_match':'Exact full name and Flowing title agree with captured biography; journal and named newspaper blog cross-confirm writing identity.', 'poems_read':[446],
'limitations':['Nissim award is repeated in contributor biographies but organizer record was not established; no award claim added.','Two named books are examples, not a current lifetime total. A newer Gold Dust on Sunbeams retailer lead needs publisher confirmation before adding a selected-book entry.','Ramayana reference describes the poem; no historical factual claim is inferred from its mythic narrative.'], 'next_action':'Verify award through organizer and current bibliography through publisher; author/editor review pending.'}
}
if __name__=='__main__':
 profiles={p['id']:p for p in json.loads((SITE/'data/writer-profiles.json').read_text())};current=json.loads((SITE/'data/writer-enrichment.json').read_text())
 for ident,item in entries.items():
  if str(ident) in current:raise RuntimeError(f'Refuse overwrite {ident}')
  reader={'sections':[{'heading':'Life and writing.','language':'en','paragraphs':item['paragraphs']}],'books':item.get('books',[]),'sources':[{k:s[k] for k in ['label','url']} for s in item['sources']],'reviewed_on':DATE}
  record={'writer_id':ident,'name':profiles[ident]['name'],'reviewed_on':DATE,'batch':'research-005','status':item.get('status','source_checked_local_draft'),'independent':False,'portrait_action':'unchanged','reader_draft':reader,**{k:v for k,v in item.items() if k not in ['paragraphs','books','status']}}
  record['limitations'].append('Same-assistant research/interpretation; author/editor factual review pending.')
  (HOME/'enrichment'/f'{ident}.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n');current[str(ident)]=reader;(SITE/'data/writer-enrichment.json').write_text(json.dumps(current,ensure_ascii=False,indent=2)+'\n');print('Saved writer',ident)
