"""Close the verified all-edition rollout after the final live receipt exists."""
import json,sys
from pathlib import Path
from datetime import datetime,timezone
R=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else Path(__file__).resolve().parents[3];K=R/'kb/research/edition-art-rollout-2026-10-04';now=datetime.now(timezone.utc).isoformat()
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
q=json.loads((K/'queue.json').read_text());assert all(e['status']=='published_verified' for e in q['editions']);assert q['active_batch'] is None and q['next_edition'] is None
v=json.loads((K/'checkpoint-2-1-live-verification.json').read_text());a=json.loads((K/'final-provenance-audit.json').read_text());assert v['result']==a['result']=='PASS';assert a['accepted_artworks']==140 and len(a['held'])==1
q.update(status='completed_with_hold',completed_at=now);q['counts'].update(accepted_artworks=140,text_led_openings=139,preserved_candidates=157);save(K/'queue.json',q)
p=R/'kb/records/edition-art-rollout-2026-10-04.json';r=json.loads(p.read_text());r.update(status='completed_with_hold',completed_at=now,counts=q['counts'],next_action='All47 editions are published and verified. No generation or publication pending. One edition6 block-tower image remains excluded; its poem retains existing artwork. Independent editorial review remains separate.',final_verification='research/edition-art-rollout-2026-10-04/final-provenance-audit.json',holds=a['held'],loop_status='completion_verified_awaiting_pause');save(p,r)
p=R/'kb/registers/records.json';d=json.loads(p.read_text());w=next(x for x in d['work'] if x['id']=='KBL-WORK-022');w.update(status='completed',readiness='applied',next_action='All47 editions live:140 illustrations and139 text-led openings. One edition6 artwork held for geometry; existing poem art preserved. Independent editorial review remains separate.');w['evidence']=list(dict.fromkeys(w['evidence']+['records/edition-art-checkpoint-2-1-publication-2026-10-04.json','research/edition-art-rollout-2026-10-04/final-provenance-audit.json']));save(p,d)
p=R/'kb/registers/activity.jsonl';events=[json.loads(s) for s in p.read_text().splitlines() if s.strip()];eid=max(int(x['id'].split('-')[-1]) for x in events)+1
with p.open('a') as f:f.write(json.dumps(dict(id=f'KBL-EVT-{eid:03}',recorded_at=now,actor=dict(kind='ai_assistant',name='Current assistant; same-assistant completion audit'),summary='Completed all47-edition artwork rollout:140 accepted illustrations and139 text-led openings published and verified.157 candidate masters retained with exact prompts, poem snapshots and hashes. One edition6 block-tower image is held after two corrections; existing poem art preserved. Final publication and provenance audit pass; independent:false. Heartbeat ready to pause after final handoff synchronization.',refs=['KBL-WORK-022','KBL-DEC-046'],evidence=['research/edition-art-rollout-2026-10-04/final-provenance-audit.json','records/edition-art-checkpoint-2-1-publication-2026-10-04.json'],next_action='Synchronize handoff and pause the completed artwork heartbeat.'))+'\n')
print('All47 editions complete; one excluded artwork hold retained.')
