"""Close a visually reviewed edition and record an exact next batch; no publication claim."""
import json,sys
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;n=int(sys.argv[1]);now=datetime.now(timezone.utc).isoformat();p=K/f'batches/edition-{n}/batch.json';b=json.loads(p.read_text());v=json.loads((p.parent/'verification.json').read_text());assert v['result']=='PASS';assert all(i['status']=='integrated_local' for i in b['items'])
b.update(status='verified_local_pending_publication',completed_at=now,updated_at=now,checks=dict(public_build='PASS',source_cover_reader_integrity='PASS1453protected files;833reader variants;799controls;17pilot entries unchanged',edition_integrity='PASS',visual=f'All3masters reviewed at normal size; desktop and360px illustrated/text-led pages visually inspected; desktop-{n}.png and mobile-{n}.png. Same-assistant review.',publication='Awaiting authorized three-edition checkpoint'))
p.write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');p=K/'queue.json';q=json.loads(p.read_text());ed=next(x for x in q['editions'] if x['edition']==n);ed.update(status=b['status'],verified_at=now,next_artwork=None);q['active_batch']=None;q['next_edition']=next((x['edition'] for x in q['editions'] if x['status']=='pending_planning'),None);q['updated_at']=now
completed=[x for x in q['editions'] if x['edition']<45 and x['status'] in ('verified_local_pending_publication','published_verified')];pending=[x for x in q['editions'] if x['status']=='pending_planning'];q['counts'].update(remaining_editions=len(pending),new_rollout_artworks=sum(len(x['artworks']) for x in completed),verified_local_unpublished_editions=sum(x['status']=='verified_local_pending_publication' for x in completed),estimated_remaining_artworks=3*len(pending));p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
p=R/'kb/records/edition-art-rollout-2026-10-04.json';r=json.loads(p.read_text());r.update(counts=q['counts'],last_completed_batch=f'edition-{n}',next_action=f'Resume edition{q["next_edition"]}; publish the next three verified unpublished editions together. {q["counts"]["published_editions"]} editions are live.',handoff_note='Synchronizing this completed edition checkpoint; preserve concurrent portrait files.');p.write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
p=R/'kb/registers/activity.jsonl';events=[json.loads(s) for s in p.read_text().splitlines() if s.strip()];eid=max(int(x['id'].split('-')[-1]) for x in events)+1
with p.open('a') as f:f.write(json.dumps(dict(id=f'KBL-EVT-{eid:03}',recorded_at=now,actor=dict(kind='ai_assistant',name='Current assistant; Anvesha art direction, Samanta implementation and Drishti self-review'),summary=f'Edition{n}: read all{len(b["poems_read"])} poems, created3 distinct Human Natural / Poetic Natural illustrations and3 text-led openings. Full source snapshots, prompts, hashes and independent:false reviews retained. Public build,1453protected files,833reader variants,799controls and desktop/mobile visual checks pass. Local verification complete; awaits authorized checkpoint publication. Separate portraits untouched.',refs=['KBL-WORK-022','KBL-DEC-046'],evidence=[f'research/edition-art-rollout-2026-10-04/batches/edition-{n}/verification.json'],next_action=r['next_action']))+'\n')
print(q['counts'],r['next_action'])
