"""March planning after reading the available poems and respecting the unlisted record; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-41';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True)
rows=[
(725,'a-little-sky','A little room for sky','Selfie moves through memory, constriction and departure; the small glimpse of sky offers breathing room. Avoid a phone, a literal magic carpet, funeral spectacle or a biographical figure.',
'A restrained watercolor and graphite architectural fragment seen looking upward from an ordinary shaded interior toward a high opening. Two close off-white plaster planes frame only a narrow irregular glimpse of silver-blue morning sky, slightly off-centre right. A thin pale cotton curtain edge has moved a little in the breeze at the near side, partly cropped, gravity still clear. Do not show a whole room, furnished window sill, plants, birds, clouds as symbols or a staged view. Quiet dry graphite edges with occasional softened watercolor transitions. Mostly pale warm-grey paper space, the little sky patch a cool lucid note. Natural light reveals the inner wall softly and fades into the near interior, no beams or decorative weathering. Suggest release through small space rather than imprisonment or decay.'),
(728,'after-the-bulletin','After the bulletin','Wasted Penance places public war rhetoric against private fear and waiting. Focus on the room after the news, leaving violence and patriotism in the words rather than making them a spectacle.',
'A small ordinary portable transistor radio sits near the edge of a plain table, seen close from a seated angle. Radio is switched off; a dark unlit rectangular tuning window has no readable markings, with one simple knob and a modest cloth speaker grille. A partly folded unprinted grey newspaper-like sheet is cropped at the far edge, softly suggested, without photographs or headlines. No flags, weapons, medals, blood, national emblems, candle, flowers or people. A quiet ink-wash and muted umber gouache drawing, low chroma with enough clean daylight from the left to distinguish the object. Large unelaborated wall area above. Physical contact and a slight table shadow, grille described selectively rather than each hole repeated. Emotional stillness and helpless waiting, never picturesque gloom or an antique product advertisement.'),
(729,'life-at-the-margin','What grows unasked','The field is green reveals hidden interdependent life, then ends with a wish for a mower. Let attention rest on overlooked growth beside a recently cut margin, rather than illustrating every insect or the mower itself.',
'A low close painted view across an irregular patch of ordinary weeds and seed heads at the edge of a green field after night rain. Only one near leaf catches transparent pale early light, while overlapping lower leaves conceal much of the ground. At the extreme right foreground, a narrow less detailed strip of recently cut grass enters the crop, a quiet interruption rather than an obvious split composition. No mower, humans, showy flowers, butterflies, insects posed for inspection, jewel droplets or glittering web. Soft green watercolor with a little dry coloured-pencil line and ivory paper showing through; tangled vegetation is selective, not every leaf resolved. A few stems lean differently from their neighbours. Light and leaf translucency are physically coherent; rich living detail is concentrated near the lit leaf, distant field stays a simple wash. Patient curiosity with an undertone of vulnerability.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-41/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue41. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No people, portraits, readable text, signature, logos or watermark. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=41,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-41/{ident}/v1.png',attempts=[],independent=False))
plain=[dict(poem_id=731,rationale='An imperfect mother speaks in her own voice; a generic parent-child picture would idealise the very relationship she complicates.',status='pending'),dict(poem_id=732,rationale='The persistent questioning and claim to humanity work through lineation; avoid assigning a face, caste or religious emblem.',status='pending'),dict(poem_id=730,rationale='Leave absence and its shifting wound metaphor unresolved, without an invented romantic scene.',status='pending')]
for p in (S/'content/editions/issue-41').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=41,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-41').glob('poem-*.json')),direction='Making room to notice: a narrow sky opening, the silence after a news bulletin, and overlooked field life. Distinct spatial scales and media support memory, political grief and attention. Preserve the existing bespoke date-gift illustration for724; do not assign the unlisted727 source. New interpretation, not a historical editorial theme.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==41);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-41',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition41 planned; all11 available source snapshots retained,10 listed poems eligible.')
