"""August planning after reading all twenty-three poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-10';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True,exist_ok=True)
rows=[(263, 'colours-for-a-life-continuing', 'Colours for a life continuing', 'The poem ends with two people living differently under one sky: one writes and the other draws with a child. A used drawing book can carry that continuing creative life without depicting or inventing them.', 'Horizontal 3:2 colored pencil and soft gouache still life, close oblique view of an ordinary open unlined drawing exercise book partly cropped at lower right on a plain matte table. On the right page a few simple hesitant colored-pencil bird shapes among two uneven branch lines, clearly childlike drawings within the painted scene, not real birds or text. Three short differently worn colored pencils lie loosely near the bottom page edge, not a display fan. One faint erased contour shows revision. Quiet pale unoccupied tabletop at upper left; soft ordinary side daylight, plausible page fold, pencil contact and shadows. No adult hand, child, ink writing, labels or overfilled craft props.'), (266, 'light-through-the-cleared-glass', 'Light through the cleared glass', 'The speaker finds an inner companion who clears sorrow like soot from lantern glass. A restrained study of the glass and light preserves this self-renewal without literal magical people or a collection of the poem’s flowers.', 'Horizontal 3:2 charcoal and muted translucent watercolor study of one simple kerosene hurricane lantern standing securely on a plain low ledge, cropped close at the right edge. Correct coherent metal frame, rounded clear glass globe held between metal base and vented cap, very small steady warm wick flame near the bottom inside glass. Glass mostly clean; faint soot only high inside near vent, not smeared dirt all over. Quiet cool-grey room beyond with generous empty left space; weak ambient daylight, flame only warms nearby glass/base. No dramatic halo, sparkles, extra lamp, cleaning hand or rag props. Focus on transparency and a small practical light rather than picturesque age.'), (253, 'the-wave-that-returns', 'The wave that returns', 'The poem senses a lost loved one in the sea’s repeated touch. A close shore fragment gives that returning movement room without staging a grieving person or a grand sunset.', 'Horizontal 3:2 thin oil and palette-knife study on matte paper. Look down at a shallow clear turquoise wash of seawater as it recedes across ordinary pale golden sand. An uneven narrow foam fringe cuts diagonally through lower left and breaks in a few places; broad quiet damp sand at right, tiny reflected sky accents only where water is thin. No horizon, sunset, distant landscape, footprints, shells, people, blood or decorative stones. Bright soft morning light, restrained sand and pale blue-green, translucent water with believable gentle slope and gravity. Selective thicker paint at a short foam edge, rest spare and smooth; no equal microdetail.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-10/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue10. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No identifiable real people, portraits, readable text, signature, logos or watermark. No people, portraits or documentary location claims. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=10,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-10/{ident}/v1.png',attempts=[],medium_label={263:'colored pencil and gouache',266:'charcoal and watercolor',253:'oil and palette knife'}[pid],independent=False))
plain=[{'poem_id': 246, 'rationale': 'The first-person appeal against female infanticide remains text-led; no invented child or sensational harm image.', 'status': 'pending'}, {'poem_id': 249, 'rationale': 'The indictment of gendered honour and belonging needs the full speaking voice, not a generic female victim illustration.', 'status': 'pending'}, {'poem_id': 267, 'rationale': 'The poem invokes uncounted train passengers and wounded landscapes; avoid inventing documentary disaster imagery or reducing its critique to an umbrella prop.', 'status': 'pending'}]
for p in (S/'content/editions/issue-10').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=10,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-10').glob('poem-*.json')),direction='August finds continuing life in a revised drawing, cleared lantern glass and a returning wave. Colored pencil, charcoal with transparent wash, and thin oil vary material and viewpoint. The poems confronting gendered violence and uncounted loss stay text-led.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==10);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-10',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition10 planned; all23 source snapshots retained.')
