"""April planning after reading all fourteen poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-42';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True)
rows=[
(736,'colours-meet','After the shared colour','The Holi poem joins estranged people through shared celebration. Evoke the ordinary aftermath of meeting, not a staged festival advertisement or a crowd of invented faces.',
'A close oblique painted view of a small patch of clean stone paving just inside an open courtyard after Holi. Two modest traces of rose-pink and warm yellow gulal meet where a little rinse water has travelled between paving joints. At the far left edge crop one shallow plain steel basin containing slightly tinted water; only a third of it visible, naturally resting flat. No arranged powder mounds, perfectly round bowls, flowers, footprints, confetti or people. Bright soft daylight, gently reflected by the water, without glitter. Loose transparent watercolor with a few firmer gouache notes for pink pigment and a faint graphite joint line. More than half the image is pale neutral stone. The colour has a physical origin and flows downhill subtly, never becoming a rainbow swirl. Fresh joyful human connection, not grime or decorative distress.'),
(739,'slow-company','A small pace through green','Hold On places patient small lives beside mortality. Choose the first easy-going slug among tiny flowers as one quiet encounter; leave the other haiku images to the language.',
'An intimate spare watercolor nature study from almost ground height: one ordinary small brown slug travels through low moss beside two tiny inconspicuous white woodland flowers, one partly hidden behind grass. A few irregular moss stems in foreground and gentle pale green shadow beyond, no glowing forest or miniature fantasy. The slug has a soft continuous moist body in contact with the ground, a small pair of upper tentacles and subtle shorter lower feelers; no shell, eyes drawn on stalk tips or human expression. It occupies less than one fifth of the width, slightly left of centre, moving into open pale space. Delicate ink contours only at the near body and selected stems, most greenery washes into untouched ivory paper. Neither everything sharp nor dew jewels. An unhurried living moment, understated and beautiful.'),
(740,'what-the-tide-takes','After the retreat','Game of Sea shifts from apparently friendly waves to what they carry away and expose. Make absence perceptible through the shore, without a literal bone or treasure tableau.',
'A horizontal low coastal study looking obliquely down along a stony shore at ebb. The near half holds a few partly embedded smooth grey pebbles with naturally irregular spacing and one short exposed weathered root fragment at the far edge; scattered smaller stone marks are economical. A thin subdued arc of retreating seawater crosses the upper right, leaving darker wet sand and several shallow vacant stone impressions nearer the centre. No shells displayed in a row, precious gems, human bones, travellers, dramatic cliffs or crashing surf. Quiet diffuse daylight. Muted blue-grey watercolor and rubbed graphite, broad areas of unmarked pale sand, selective dark wet edges where water actually contacts stone. Sense of an exchange just completed, restrained movement and spaciousness rather than a postcard beach.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-42/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue42. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No people, portraits, readable text, signature, logos or watermark. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=42,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-42/{ident}/v1.png',attempts=[],independent=False))
plain=[dict(poem_id=733,rationale='The short life-reckoning moves between mathematics and grief; let its lineation carry those transitions without an equation collage.',status='pending'),dict(poem_id=744,rationale='The ironic turn from danger in darkness to wounds in daylight gains force without depicting ghosts, snakes or a literal menacing street.',status='pending'),dict(poem_id=746,rationale='Keep the demand for privacy and agency in the words; avoid a voyeuristic woman image or a literal four-panel metaphor.',status='pending')]
for p in (S/'content/editions/issue-42').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=42,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-42').glob('poem-*.json')),direction='Small traces, shared life: bright festival colour, a patient creature close to the ground, and a shore after withdrawal. Vary scale, saturation and mark-making; a new interpretive direction, not a historical editorial theme.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==42);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-42',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition42 planned; all14 source snapshots retained.')
