"""September planning after reading all seventeen poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-11';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True,exist_ok=True)
rows=[(270, 'the-space-between-marks', 'The space between marks', 'The poem values silence, discontinuity and imperfection. An abstract brush drawing lets intervals carry the feeling rather than illustrating breathing, sin and dust as objects.', 'Horizontal 3:2 original abstract ink-and-graphite literary drawing on clean warm ivory paper. One loose intermittent rising and falling gesture crosses only the lower middle third, made with a few short tapered ink brush marks and faint graphite connections that stop and resume. Widely unequal intervals, varying pressure, one small cluster of marks and a long open pause. It must feel like someone listening and finding rhythm, not typography or a plotted waveform. No letters, Morse code, musical notation, graphs, equal rows, decorative splatter or grunge. Upper half largely empty; selective attention to a few ink edges where pigment meets paper.'), (276, 'the-distance-around-a-lotus', 'The distance around a lotus', 'The speaker imagines a lotus beyond the restless beloved’s reach. Let still water and distance carry the unfulfilled relation; omit the bee rather than invent an embrace.', 'Horizontal 3:2 pale watercolor study, oblique close view across quiet grey-green pond water. A single small imperfect pink lotus at the far right third rises on a plausible slender stem above water; petals overlap unevenly, side-facing rather than a perfect frontal rosette. One partial broad lotus leaf cropped at right, not a lily pad supporting the blossom. Most of the frame is quiet pale water with barely visible soft reflected flower color directly beneath it. Soft overcast light, no theatrical sun, perfect mirror reflection, insects, ornamental droplets, repeated blooms or botanical diagram. Keep flower modest and water expansive, restrained rose and grey-green pigment on opaque ivory paper.'), (283, 'shadows-enter-the-clearing', 'Shadows enter the clearing', 'The poem begins with pine shadows and makes perception uncertain. A cropped woodland floor with shadows can suggest that uncertainty without assembling its cosmic and geological images into spectacle.', 'Horizontal 3:2 hand-cut two-color woodcut with a light ochre wash. Look down at a quiet patch of forest floor: cropped shadows of two off-frame pine branches extend diagonally from the upper left, one thicker soft trunk shadow reaches across only part of the frame. Shadow shapes coherent with one low daylight direction, uneven overlapping branch spacing and broken needle silhouettes. No actual tree trunks, horizon, sky, stars, birds, volcanoes or bonfire. Warm pale ochre ground largely unmarked toward the right; muted charcoal-grey shadow ink with selective carved marks, not uniform digital scratch texture. Evoke uncertainty through incomplete shadows at frame edges, never an evenly repeating decorative pattern.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-11/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue11. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No identifiable real people, portraits, readable text, signature, logos or watermark. No people, portraits or documentary location claims. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=11,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-11/{ident}/v1.png',attempts=[],medium_label={270:'ink and graphite',276:'watercolor',283:'woodcut and wash'}[pid],independent=False))
plain=[{'poem_id': 269, 'rationale': 'The plea to visit ageing parents is carried by the voice; avoid stock images of lonely parents or an invented family.', 'status': 'pending'}, {'poem_id': 272, 'rationale': 'The epic argument about justice remains text-led, avoiding newly invented devotional battle iconography.', 'status': 'pending'}, {'poem_id': 274, 'rationale': 'Pandemic bereavement and a daughter rebuilding her life deserve the complete poem without an invented mourner or hospital scene.', 'status': 'pending'}]
for p in (S/'content/editions/issue-11').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=11,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-11').glob('poem-*.json')),direction='September explores pauses and uncertain connections: an interrupted ink gesture, a lotus held at a distance, and partial pine shadows. Abstract drawing, pale watercolor and restrained woodcut give distinct readings without a collage of poetic nouns. Family separation, epic justice and bereavement stay text-led.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==11);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-11',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition11 planned; all17 source snapshots retained.')
