"""January planning after reading all seven poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-15';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True,exist_ok=True)
rows=[(341, 'first-rain-on-dry-earth', 'First rain on dry earth', 'An unexpected meeting moistens the speaker’s dry inner sky. Close rain touching earth suggests that first inward change without inventing the two people or assembling the poem’s lightning, ice and stars.', 'Horizontal 3:2 low oblique close study in granulating watercolor and soft graphite. A few fresh drops darken a patch of pale dry earth, uneven small damp marks beginning to join in one place while most of the surface remains dry. One tiny green shoot appears at the edge, partially cropped and unspectacular. Restrained earth pinks, umber and grey-blue; no cracked desert pattern, jewel droplets, splash crown, rain streak curtain, horizon, storm sky or dramatic spotlight. Overcast light, causal wet darkening with softer edges as water absorbs. Broad open dry ground and a tentative, intimate feeling of contact; no decorative clutter.'), (344, 'the-river-held-in-a-bottle', 'The river held in a bottle', 'The ode contrasts the river’s indifferent continuity with sacred water enclosed and sold. One ordinary bottle beside a broad river wash suggests that tension without reconstructing Kashi, funeral rites or monuments.', 'Horizontal 3:2 quiet gouache with graphite accents. An ordinary small clear reused bottle, capped with a plain muted screw cap and containing a little water, stands off-center on a cropped stone river-step surface. Low side view, broad blurred grey-green moving river beyond, far bank omitted. Bottle is modest and utilitarian, no label, embossing, readable text, advertising shine or ornamental ritual arrangement. Water has a consistent horizontal level; glass refraction slightly distorts the stone edge visible through it, soft shadow at base. No temple, person, corpse, pyre, boat, flame or exact ghat/location claim. Pale diffuse daylight and large quiet water field; sacredness and commerce left ambiguous rather than glamorized.'), (346, 'above-the-dark-water', 'Above the dark water', 'The poem locates freedom in a lotus emerging from dark water. A sideward flower partly withheld by its leaf keeps that awakening grounded rather than a centered sacred emblem.', 'Horizontal 3:2 softly brushed oil pastel and thin watercolor pond study from near water level. One modest pale pink lotus rises on a narrow natural stem just left of center; view it partly side-on, with some outer petals overlapping and hiding the center. A broad green leaf, obliquely cupped above the water, is cropped at right and partly overlaps the lower stem. Dark olive-grey water remains mostly empty, only slight broken reflections close to the stem and leaf; no mirror-perfect flower reflection. No symmetrical mandala, statue, aura, jewel dew, floating petals or flower garden. Petals have gentle uneven spacing and restrained value, selective soft edges. Quiet liberation, real growth and depth, not a luxury spa icon.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-15/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue15. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No identifiable real people, portraits, readable text, signature, logos or watermark. No people, portraits or documentary location claims. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=15,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-15/{ident}/v1.png',attempts=[],medium_label={341:'watercolor and graphite',344:'gouache and graphite',346:'oil pastel and watercolor'}[pid],independent=False))
plain=[{'poem_id': 340, 'rationale': 'The poem names a lost riverbank community and its transformation; preserve its testimony without fabricating a documentary reconstruction or deity.', 'status': 'pending'}, {'poem_id': 343, 'rationale': 'The direct argument for equity at home is strongest as an open address; avoid symbolic gender stereotypes.', 'status': 'pending'}, {'poem_id': 347, 'rationale': 'The sharp shifts among self-doubt, a remembered death, detergent and anxiety should stay in the language; avoid depicting the named woman or reducing the poem to household props.', 'status': 'pending'}]
for p in (S/'content/editions/issue-15').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=15,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-15').glob('poem-*.json')),direction='January moves through three kinds of contact with water: first rain on dry earth, a river reduced to a bottle, and a lotus rising from dark water. Close material study, a spare object-and-river composition and a low pond view give distinct emotional and visual scales. Ecological testimony, equity and the difficult turns of self-doubt remain text-led.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==15);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-15',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition15 planned; all7 source snapshots retained.')
