"""Record a poem-informed June batch after reading all11 poems."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-44';B.mkdir(parents=True,exist_ok=True);S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
assert not (B/'batch.json').exists(),'Resume existing batch'
poems={json.loads(p.read_text())['id']:(p,json.loads(p.read_text())) for p in (S/'content/editions').glob('*/poem-*.json')}
rows=[(765,'daily-warmth','The small daily ceremony','A close, slightly overhead watercolor study of an ordinary home breakfast just prepared: a simple glazed teacup on its saucer with a small piece of toast on a steel side plate, cropped at the edge of a clean pale kitchen counter. A used teaspoon has been laid naturally across the saucer rim. No teapot, books, writing desk, flowers or shop setting. Pale morning light, warm grey and a touch of tea brown, almost all background left open. The objects need not match. No dramatic steam. Let a few economical graphite lines meet soft transparent washes, less filled-in than a realistic still life.','The recurring tea-and-toast ritual expresses care in a long marriage without inventing a couple or romantic spectacle.'),(767,'river-after-rain','What the water leaves','A broad open watercolor landscape of a shallow seasonal riverbed after water has receded, viewed at a modest high bank angle. Thin irregular traces of damp earth lead through pale sediment; small patches of young green growth begin on the former channel. Low banks, no imposing mountains, no bridge, boat, flood spectacle, people or flowers arranged for display. Soft pale-grey earth and restrained moss-green washes with a few graphite contour marks; open daylight. Suggested forms, not every pebble described.','The poem moves from temporary division to fertile connection; a recovering riverbed leaves the daughter metaphor in the words.'),(763,'rain-colour','A quieter colour','An intimate low watercolor-and-graphite glimpse of a small plain white butterfly resting side-on on a narrow grass blade after light rain. Both folded wings form a single believable silhouette, body and fine legs modestly suggested rather than enlarged. Grass emerges from damp brown-grey earth; sparse overlapping stems, no bed of flowers, no dew diamonds, no rose, no sunburst. Very pale cool-grey and softened green washes leave substantial ivory paper untouched. White wing is reserved paper with one thin soft edge; no black decorative pattern. Selective marks near the resting insect, surroundings dissolve into quiet wash.','Choose the closing search for rain-coloured tenderness after the poem rejects spectacular colours; avoid picturing injury or a biographical woman.')]
items=[]
for pid,ident,title,scene,reason in rows:
 p,d=poems[pid];snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal3:2 poem illustration for Kabita Live Issue44. Apply Human Natural in Poetic Natural mode. Clearly hand-directed watercolor and restrained graphite on ivory paper, not photographic simulation.\nEmotional purpose: {reason}\nScene: {scene}\nAvoid evenly distributed detail, symmetrical styling, decorative distress, global grain, artificial cinematic light and repetitive paper effects. Believable material contact, scale and light. No people, written words, signature or watermark. This is an interpretation of {d["title"]} by {d["author"]}, not a documentary scene or author endorsement. Opaque cream-paper background.\nPoem context, read in full; never render this text:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append({'id':ident,'edition':44,'poem_id':pid,'title':title,'rationale':reason,'status':'pending','prompt':str(pp.relative_to(R)),'poem_source':str(p.relative_to(R)),'poem_evidence':str(snapshot.relative_to(R)),'poem_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'output':f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-44/{ident}/v1.png','attempts':[],'independent':False})
plain=[{'poem_id':762,'rationale':'Let the cadence and direct address of the Hindi couplets stand without a stock couple or floral emblem.','status':'pending'},{'poem_id':768,'rationale':'The changing mortality metaphors need room; avoid a literal map-and-clock collage.','status':'pending'},{'poem_id':770,'rationale':'Keep the dramatic voices and resilience in the poem instead of an ornamental phoenix.','status':'pending'}]
for i in plain:
 p,d=poems[i['poem_id']];(B/f'poem-{i["poem_id"]}.json').write_bytes(p.read_bytes())
batch={'edition':44,'status':'planned','created_at':now,'poems_read':[x for x,(p,d) in poems.items() if d.get('edition')==44],'direction':'Care and what remains: pale grey earth, quiet green and restrained tea warmth; intimate domestic ritual, broad changing ground and a near-weightless insect study. New interpretation, not a historical edition theme.','items':items,'text_led':plain,'independent':False}
(B/'batch.json').write_text(json.dumps(batch,ensure_ascii=False,indent=2)+'\n');p=K/'queue.json';q=json.load(open(p));entry=next(x for x in q['editions'] if x['edition']==44);entry.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=batch['direction']);q['active_batch']={'id':'edition-44','owner':'current-chat-assistant','started_at':now,'status':'running'};p.write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n');print('Read11poems; three distinct commissions and three text-led pages planned.')
