"""June planning after reading all seventeen poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-8';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True,exist_ok=True)
rows=[(214, 'three-sparrows-at-the-window', 'Three sparrows at the window', 'The return of three sparrows restores trust and affectionate attention. Show their ordinary visit, not birds performing affection or an invented grieving speaker.', 'Horizontal 3:2 warm watercolor with selective pencil. Exactly three small ordinary brown sparrows perch at uneven distances on a plain exterior window ledge seen from inside, only one slim cropped frame edge visible at left. One bird is side-on, one turned partly away, third nearer edge with head lowered; wings folded, feet grip the ledge naturally. Plausible brown/grey feather masses with details only on nearest head and wing. Soft overcast daylight, muted green outdoors beyond, broad quiet pale interior area at left. No people, feeder, flowers, hearts, theatrical rays, all three facing viewer, repeated cloned birds, readable text or added bird silhouettes.'), (226, 'the-small-world-on-a-leaf', 'The small world on a leaf', 'The granddaughter’s attention to a cicada gives the adult a child’s view again. A close encounter with the insect on a leaf conveys discovery without inventing the child, a hand or a documentary view of Wellington.', 'Horizontal 3:2 intimate graphite and very light watercolor naturalist sketch on opaque ivory paper. A single small cicada rests side-obliquely on an ordinary green leaf whose stalk continues out of frame. Coherent compact cicada body, short antennae, two pairs of translucent veined wings overlapping roof-like above abdomen, six legs attached to thorax with near legs gripping leaf and far legs partly occluded. Do not splay wings flat like butterfly, do not add dragonfly body. Selective essential detail on body and near wing; far wing fades softly, much paper unmarked, no botanical labels, child, hands or exact species/location claims. Wonder through attentive looking, not scientific plate perfection.'), (227, 'jasmine-on-still-water', 'Jasmine on still water', 'The poem’s remembered rose becomes jasmine floating in a bowl. A quiet close view of that later flower can hold the changed life and memory without inventing Najifa or her family.', 'Horizontal 3:2 soft pastel with thin gouache accents. Close oblique view of a modest shallow plain dark ceramic bowl partly cropped at lower right on a subdued rose-grey surface. Still water fills bowl below rim; a single small off-white jasmine blossom and one separated petal float naturally near one side, not precisely centered. Bowl ellipse and waterline consistent with viewpoint, reflection subdued and broken by flower, flower supported by surface tension. Cool soft daylight from left, one tiny highlight on rim, surrounding area calm and largely unworked. No rose, portrait, prayers, text, ritual symbols, decorative jewelry, candles or staged botanical arrangement. Allow darkness within bowl without making entire scene gloomy.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-08/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue8. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No identifiable real people, portraits, readable text, signature, logos or watermark. No people, portraits or documentary location claims. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=8,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-8/{ident}/v1.png',attempts=[],medium_label={214:'watercolor and pencil',226:'graphite and watercolor',227:'pastel and gouache'}[pid],independent=False))
plain=[{'poem_id': 220, 'rationale': 'The political accusation and questioning of power remain text-led, without assigning an invented face to the mastermind.', 'status': 'pending'}, {'poem_id': 224, 'rationale': 'The intimate and ambiguous address to God remains text-led; no literal deity or devotional icon is added.', 'status': 'pending'}, {'poem_id': 230, 'rationale': 'The woman’s decision and self-respect are voiced directly; no generic heroic portrait or invented identity substitutes for her words.', 'status': 'pending'}]
for p in (S/'content/editions/issue-08').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=8,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-08').glob('poem-*.json')),direction='June invites attentive looking at three returning sparrows, a cicada seen with childhood curiosity and jasmine holding a changed memory. Warm watercolor, spare graphite and a close pastel study shift scale and density. Political accusation, divine absence and women’s agency stay text-led.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==8);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-8',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition8 planned; all17 source snapshots retained.')
