"""February planning after reading all ten poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-16';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True,exist_ok=True)
rows=[(350, 'after-the-fair-noise', 'After the fair noise', 'The poem moves from the crowded Bali Jatra of life toward a lonely walk home with peanuts. A small packet at the quiet edge of the fair keeps that ordinary aftertaste without inventing the named speaker or beloved.', 'Horizontal 3:2 soft chalk pastel and thin gouache. A partly folded plain brown paper cone containing a few unshelled peanuts rests on a low flat ledge at the edge of an indistinct open fairground after dusk. Close oblique crop: packet at lower left, loosely creased paper holding its weight, a couple of peanuts partly hidden inside. Beyond it, a broad quiet grey-violet plane and just two faint warm distant stall lights, not bokeh confetti. No balloons, boats, people, signage, printed paper or decorative rubbish. Ordinary solitude after noise; not a product still-life. No location accuracy claim. Muted warm brown and violet, simple causal soft ambient light.'), (355, 'rain-in-an-unfamiliar-lane', 'Rain in an unfamiliar lane', 'Alienation remains even when a city briefly touches the speaker. An unclaimed wet lane and cropped tall facades convey distance without fabricating a recognizable city or person.', 'Horizontal 3:2 loose ink and grey-green watercolor architectural study. Eye-level view along a narrow ordinary city lane after rain, asymmetrically cropped unadorned building walls rising out of frame, no landmarks or readable signs. A thin shallow puddle follows an uneven edge in the paving and catches only a broken pale sky reflection; some ground stays dull and wet. Lane turns before the distance, so there is no perfect vanishing-point spectacle. One dark doorway is closed; no person, vehicle, ornamental flower display or theatrical illumination. Restrained ink on selected joins, other edges lost into pale wash. Quietly unfamiliar rather than dystopian or picturesque decay.'), (357, 'small-twigs-at-evening', 'Small twigs at evening', 'The poem ends by picking twigs of hope after an extended inward struggle. Keep hope modest in a loose gathering of twigs, neither a triumphal flowering branch nor a decorative crown.', 'Horizontal 3:2 spare graphite and ochre watercolor on opaque warm ivory paper. Three small unequal plain fallen twigs lie loosely across a pale ordinary sill, two overlapping with natural contact and one separated by a little space. One tiny subdued leaf remains attached, no flowers and no glowing buds. The sill edge is partly cropped, background mostly quiet pale grey-lilac evening wash without a landscape. Side ambient light gives soft slight contact shadows; a tender pause after a difficult day, not a styled bouquet. Selective graphite strokes follow real tapering wood; no mechanical bark detail, gritty distress, text, people or hands.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-16/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue16. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No identifiable real people, portraits, readable text, signature, logos or watermark. No people, portraits or documentary location claims. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=16,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-16/{ident}/v1.png',attempts=[],medium_label={350:'chalk pastel and gouache',355:'ink and watercolor',357:'graphite and watercolor'}[pid],independent=False))
plain=[{'poem_id': 349, 'rationale': 'The antiwar address depends on its forceful argument; avoid fabricated civilian suffering or a literal demon.', 'status': 'pending'}, {'poem_id': 351, 'rationale': 'The shifting meaning of a smile should remain unresolved in words, without inventing a smiling person.', 'status': 'pending'}, {'poem_id': 354, 'rationale': 'A named Hyderabad hill and its monuments need factual visual research beyond this interior-art scope; retain the poem as a text-led journey without invented landmark geography.', 'status': 'pending'}]
for p in (S/'content/editions/issue-16').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=16,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-16').glob('poem-*.json')),direction='February holds solitude in three ordinary places: a peanut packet after the fair, an unfamiliar rain-wet lane, and small twigs gathered at evening. Soft pastel, architectural ink wash and sparse graphite vary texture and density. The antiwar address, elusive smile and named city landmarks remain text-led.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==16);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-16',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition16 planned; all10 source snapshots retained.')
