"""January planning after reading all seventeen poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-39';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True)
rows=[
(693,'time-beneath-roots','Time beneath the branches','The banyan addresses human anxiety about time against the continuity of shared shade. Show its living architecture at an ordinary human scale, not an immortal fantasy tree or a crowd of symbolic inhabitants.',
'A quiet ground-level view beneath a mature Indian banyan canopy. Several aerial roots descend with irregular spacing, one thicker rooted column near the left partly cropped, other fine strands stop above or meet the earth naturally. A modest patch of bare ground under the tree opens into diffused daylight beyond. No posed animals, birds, sages, people, shrine, garlands or picturesque bench. Broad matte gouache planes with loose charcoal contours and a few translucent green washes. Earth and root bark are selectively described; most canopy is simply overlapping dark green shapes, not individually sharpened leaves. Ordinary warm afternoon light filtered unevenly through foliage, no sunbeams, glowing roots or perfectly circular cathedral composition. A calm inhabited shade that exceeds a calendar without presenting a specific historical tree.'),
(706,'morning-ground','Room for the morning','Madhumaya asks for freedom and unforced life, including a cared-for courtyard welcoming morning with jhoti-chita. Choose that single grounded gesture and leave the river, bird and night in the words. KB cultural context describes restrained white rice-paste threshold drawing within an imagined Odisha home.',
'A close, mostly top-down watercolor of an ordinary clean earthen courtyard threshold in an imagined Odisha home, with early morning light arriving diagonally from outside the frame. Only a cropped part of a simple hand-drawn white rice-paste jhoti-chita lotus curve and two petal loops are visible near the lower-left edge. The line has the slight width variation of a practiced hand on firm earth, not a printed mandala, elaborate rangoli or ornamental tiled floor. Most of the picture is warm light-brown ground, a narrow cooler band beside the threshold at the upper edge. Soft restrained ochre wash, reserved ivory marks for rice paste and a few pencil lines. No brass vessel, flowers, footwear, birds, people, deity footprints, text or added religious emblems. Quiet cared-for space and a fresh day, without staged rustic distress or symmetrical decoration.'),
(699,'ice-at-the-edge','At the edge of the ice','Glacier expresses care and alarm for vulnerable ice and life. Accompany that emotional appeal with a restrained study of melting ice; do not illustrate or assert the poem’s speculative scientific claims.',
'A horizontal watercolor-and-graphite study at the grounded edge of a glacier, viewed from nearby dark stone terrain. A low substantial mass of pale blue-white ice occupies the left two thirds, its lower surface touching rough grey rock and a small shallow runnel of meltwater along the base. Ice has compressed dull translucent planes and a few believable irregular fissures; no giant floating iceberg, geometric crystal palace or perfect blue cave. Right third opens to pale grey stony ground fading into blank paper. Diffuse cold daylight, tiny graphite accents at ice-rock contacts; most snow is reserved ivory with cool grey-blue wash, not sparkling diamonds. No animals, trees, people, microbes, prehistoric eggs, flames or global disaster collage. Quiet weight, fragility and ordinary melting; clearly a literary interpretation, never scientific evidence or a named location.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-39/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue39. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No people, portraits, readable text, signature, logos or watermark. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=39,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-39/{ident}/v1.png',attempts=[],independent=False))
plain=[dict(poem_id=705,rationale='Let the woman poet’s challenge to the judging gaze stand without adding a beauty portrait or a butterfly emblem that repeats that gaze.',status='pending'),dict(poem_id=698,rationale='The kept thing is deliberately unnamed. A specific object would collapse the productive uncertainty; retain a text-led opening.',status='pending'),dict(poem_id=707,rationale='The path and the speaker trade roles through Odia wordplay; a picturesque road would over-literalise the exchange.',status='pending')]
for p in (S/'content/editions/issue-39').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=39,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-39').glob('poem-*.json')),direction='Space beyond the self: living banyan shade, a courtyard’s small act of care, and the vulnerable edge of ice. Green density, warm open earth and pale cold planes vary the visual rhythm. Keep the unnamed object and direct arguments in the words. New interpretation, not a historical editorial theme.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==39);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-39',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition39 planned; all17 source snapshots retained.')
