"""May planning after reading all twenty-one poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-7';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True,exist_ok=True)
rows=[(201, 'leaves-kept-in-a-jar', 'Leaves kept in a jar', 'The speaker hides feelings in a jar of dead leaves and learns to let go. An ordinary transparent jar can hold that inward pause without turning the poem into a portrait of despair or literal magical transformation.', 'Horizontal 3:2 muted watercolor and fine graphite still life. One small unlabelled clear wide-mouth glass jar, open and resting securely at the left third of a plain pale shelf, contains a few loosely folded dry brown leaves of uneven sizes. Leaves overlap and some are hidden, not an attractive bouquet; no flowers. Jar glass has restrained coherent rim and base ellipses, soft side-light reflections, visible shelf through empty upper glass, contact shadow under base. Most right side quiet pale-grey wall. No butterfly, person, face, mirror, written confession, excessive dirt or ornamental cracks. Transparent, introspective, gently daylight rather than theatrical sadness.'), (208, 'a-wall-being-mended', 'A wall being mended', 'The poem questions the maker who takes pleasure in repair while everything is transient. An unfinished plaster patch holds both care and provisionality, without romanticizing a ruined home or depicting the addressee.', 'Horizontal 3:2 close gouache and charcoal material study of a plain limewashed wall. A modest irregular fresh pale plaster patch covers a small former crack at lower left; two short trowel strokes visible in the damp plaster. The surrounding wall is clean muted earth-grey, not abandoned or covered in peeling paint. A cropped ordinary steel trowel rests flat on the narrow ledge below, blade lightly marked with the same plaster; handle geometry coherent. Soft lateral daylight reveals shallow relief, broad quiet wall above and right, no dramatic shafts, graffiti, words, person, hands, picturesque rubble or decorative distress. Emphasize work in progress, not perfect restoration.'), (205, 'a-kite-in-ordinary-sky', 'A kite in ordinary sky', 'The poem contrasts childhood’s small pleasures with accumulating possessions and later recognition. A modest flying kite returns attention to one simple pleasure without assembling cars, apartments and toys.', 'Horizontal 3:2 light dry-pastel sky study. A single small diamond-shaped paper kite of muted vermilion and ochre floats off-center high at left in a broad ordinary pale blue-grey afternoon sky. Paper panels and two thin bamboo spars meet coherently; a fine taut string slopes down out of the lower frame, short plain cloth tail follows the same light wind without elaborate bows. Kite slightly canted and not perfectly facing viewer. Just a faint soft cloud band near bottom, most sky quiet. No person, child silhouette, landscape, birds, text, celebratory graphics or cinematic sunset. Paper fragility and spaciousness, restrained color.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-07/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue7. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No identifiable real people, portraits, readable text, signature, logos or watermark. No people, portraits or documentary location claims. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=7,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-7/{ident}/v1.png',attempts=[],medium_label={201:'watercolor and graphite',208:'gouache and charcoal',205:'dry pastel'}[pid],independent=False))
plain=[{'poem_id': 202, 'rationale': 'The economic poem’s questions about farmers, forest communities and alternatives stay in the full voice; avoid romanticizing labour or supplying an invented policy outcome.', 'status': 'pending'}, {'poem_id': 203, 'rationale': 'The Afghanistan poem and translator credit stay text-led; do not invent a victim or documentary conflict scene.', 'status': 'pending'}, {'poem_id': 206, 'rationale': 'The song-poet’s confession about commerce and public responsibility remains text-led without a generic pen-and-coins morality illustration.', 'status': 'pending'}]
for p in (S/'content/editions/issue-07').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=7,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-07').glob('poem-*.json')),direction='May holds private feeling, provisional repair and simple pleasure in a jar of leaves, a wall being mended and a small kite. Transparent watercolor, close gouache and spacious pastel create different scales of attention. Economic questions, conflict and the poet’s public responsibility stay text-led.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==7);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-7',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition7 planned; all21 source snapshots retained.')
