"""February planning after reading all fourteen poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-40';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True)
rows=[
(721,'kept-unopened','The unspent fragrance','The soap poem turns from possessive use and diminishing substance toward leaving a fresh wrapper untouched. Focus on that final restraint rather than a beauty-product display or bathing figure.',
'A small still life in a plain home cupboard: one modest rectangular bar of soap remains fully wrapped in unprinted pale cream paper on a clean wooden shelf. View slightly from below shelf height, the far part of the shelf disappearing into gentle shade; crop the cupboard frame at the left and top rather than showing a symmetrical cabinet. Wrapper has ordinary folded seams and only a little compression at one corner, with no branding or ornamental pattern. The edge of a plain folded household cotton cloth is partly visible at far right, largely cropped. Soft ambient light enters through an off-frame open door. Thin ochre and warm-grey gouache, restrained graphite outlines, a quiet muted blue-grey shadow. Broad blank surfaces, selective detail on the closed fold. No flowers, perfume bottle, bubbles, water drops, shiny luxury styling, people or symbolic hearts. A feeling of choosing to leave something intact.'),
(712,'trace-in-brick','The trace that fades','Tacitly So asks what remains of labour, letters and trees when time erases their traces. Choose a single brick surface to give the lost maker room in the reader’s imagination, without drawing a fingerprint icon or a noun collage.',
'An oblique close detail of a low ordinary brick wall, only three differently cropped reddish-brown bricks and their lime mortar joints partly visible. One near brick has a shallow softened hand-pressed depression in its face, ambiguous and weathered, not a readable fingerprint or handprint. Slightly uneven fired clay and a few small chips arise from age and material; no picturesque ruin, moss decoration or rubble pile. Calm indirect daylight from the upper left. Earth-red ink wash with rubbed graphite and broad dry-brush clay planes on pale paper, strongest marks confined to the near depression; neighbouring brick faces fade into simple warm-grey wash. The edge of the wall recedes out of frame, believable masonry geometry. No graph paper, writing, loose letters, trees, tools or human hands. Quiet attention to ordinary labour and its disappearing evidence.'),
(718,'a-window-waits','A light still waiting','Waiting moves from the settled natural world to the breaths and prayers of those awaiting a loved one. Let a distant household light hold the feeling, without inventing a mother or wife or turning the conch call into an emblem.',
'A restrained nocturnal landscape in ink wash and watercolor. Across a modest dark hollow below low hills, a small plain house is barely suggested near the lower right; just one small window holds a dull warm lamplight. It illuminates a little of its own reveal only, not the whole landscape. The house is partly obscured by an ordinary tree silhouette. Most of the horizontal composition is quiet blue-black and muted olive-grey land merging with a very pale dark-grey night sky, no stars, moon, fog shafts, temple, people or dramatic mountains. Keep the image luminous enough to distinguish the overlapping land forms, not crushed black. Sparse edges, gentle washes and much unelaborated space. The tiny warm light is a human presence within a resting world; not a storybook cottage, luxurious interior or glowing fantasy beacon.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-40/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue40. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No people, portraits, readable text, signature, logos or watermark. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=40,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-40/{ident}/v1.png',attempts=[],independent=False))
plain=[dict(poem_id=711,rationale='Let the repeated बात ख़त्म and conversational insistence establish the intimacy without a stock romantic picture.',status='pending'),dict(poem_id=713,rationale='The reversal from looking at the trapped dove to wanting to set the trap is best left in the poem; avoid reducing it to a bird-in-cage emblem.',status='pending'),dict(poem_id=719,rationale='The accumulating political paradoxes need the cadence of the page, not a literal inventory of soldiers, lamps, classrooms and roads.',status='pending')]
for p in (S/'content/editions/issue-40').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=40,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-40').glob('poem-*.json')),direction='What is kept, what fades, what waits: an unopened everyday object, an eroding trace of labour and one light in a settled night. Three different distances, densities and emotional registers; interpretation for this rollout, not a historical editorial theme.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==40);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-40',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition40 planned; all14 source snapshots retained.')
