"""May planning after reading all fifteen poems; preserves historical issue identity."""
import json,hashlib
from pathlib import Path
from datetime import datetime,timezone
R=Path(__file__).resolve().parents[3];K=Path(__file__).resolve().parent;B=K/'batches/edition-43';S=R/'projects/site';now=datetime.now(timezone.utc).isoformat()
q=json.loads((K/'queue.json').read_text());assert q['active_batch'] is None;assert not (B/'batch.json').exists();B.mkdir(parents=True)
rows=[
(748,'album-in-trunk','The faces we keep','The poem contrasts changing, estranged life outside with faces suspended in an album. Show the act of keeping memory without inventing the people in those photographs.',
'An ordinary closed, cloth-bound family photograph album lies inside a partly open unpainted wooden storage trunk in an Indian home. Close high oblique view, album slightly obscured by the nearer lip of the trunk. Only one plain folded cotton cloth lies beside it, partly outside the crop; leave most of the interior unelaborated. No visible photographs, faces or lettering. The heavy trunk lid has plausible hinges and opens away from us; crop most of the lid rather than presenting the whole object. Modest diffuse daytime light reaches the album from off-frame left; the back interior falls softly into shade. An opaque gouache study with thin charcoal drawing on warm ivory paper: muted red-brown cloth, warm wood grey, a small dull blue in the folded fabric. Broad quiet planes and a few observed corners, not antique-shop styling, decorative patina or photorealistic wood grain.'),
(757,'fields-before-dark','Before the paths disappear','The village poem turns from labour and familiar fields toward unease at dusk. Suggest that threshold without exoticising villagers, identifying a real location, or inventing a threatening animal.',
'A horizontal field study from the edge of cultivated land near low eastern Indian foothills at late dusk. Foreground is cropped cereal stubble and dull green field growth. Narrow earthen field boundaries recede irregularly toward a low dark tree line; far hills are merely a quiet low silhouette, never mountains. View at standing eye level, broad open evening sky occupies the upper half, last light a restrained pale grey-peach near the horizon. No postcard sunset, glowing sun, neatly striped fields, buildings, people or wildlife. Dry pastel and economical charcoal over translucent earth-coloured watercolor; the near field is partially legible, farther field divisions dissolve into dark green-grey. Gentle uncertainty as familiar paths become difficult to see; darkness is natural twilight, not a horror effect. Keep some stretches visually ordinary.'),
(760,'companion-shadows','Company in the night','Haflong treats midnight shadows as supportive company and introspection rather than fear. Keep the comforting ambiguity in physical foliage shadows; do not depict spirits, dream figures or a literal rainbow.',
'An intimate nocturnal watercolor study of soft irregular leaf shadows moving across a plain pale interior wall, cast by moonlight through an unseen open window. Only a narrow fragment of a simple wooden window jamb at the far right establishes the room; no window grid, furniture, books, lamps or scenic view. Broad calm ivory and diluted indigo-grey washes, a few overlapped leaf shapes gathered off-centre low left, much wall left open. Some leaf edges clearer and others softly lost because the foliage is at differing distances. Light comes consistently from the upper right; no luminous leaf outlines, laser rays, stars, eyes or human silhouettes. A suggestion of a cool night breeze and gentle companionship. Sparse brushwork, smooth translucent wash with occasional pigment pooling at an edge, not uniform grain or an ornamental botanical pattern.')]
items=[]
for pid,ident,title,reason,scene in rows:
 p=S/f'content/editions/issue-43/poem-{pid}.json';d=json.loads(p.read_text());snapshot=B/f'poem-{pid}.json';snapshot.write_bytes(p.read_bytes())
 prompt=f'Use case: illustration-story. Original horizontal 3:2 literary artwork for Kabita Live Issue43. Human Natural in Poetic Natural mode. Preserve the selected expressive medium; a painted interpretation, never documentary evidence.\nEmotional anchor: {reason}\nScene and medium: {scene}\nAnti-optimization checks: avoid staged object display, equal detail everywhere, mechanically repeated shapes, theatrical lighting and cosmetic distress. Material contact, geometry and illumination must make sense. Preserve quiet negative space and emotional ambiguity. No people, portraits, readable text, signature, logos or watermark. Opaque ivory-paper background.\nPoem {d["title"]} by {d["author"]}; source read fully, use as context only, never render the words:\n{d["text"]}\n'
 pp=B/f'{ident}-prompt.txt';pp.write_text(prompt)
 items.append(dict(id=ident,edition=43,poem_id=pid,title=title,rationale=reason,status='pending',prompt=str(pp.relative_to(R)),poem_source=str(p.relative_to(R)),poem_evidence=str(snapshot.relative_to(R)),poem_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),output=f'kb/artifacts/artwork/edition-art-rollout-2026-10-04/edition-43/{ident}/v1.png',attempts=[],independent=False))
plain=[dict(poem_id=751,rationale='The short marital contrast is strongest as a compact verbal turn; a wedding vignette would prescribe the interpretation.',status='pending'),dict(poem_id=758,rationale='The shift from literary imitation to personal voice should be encountered directly in its ten lines, without a stock writing desk.',status='pending'),dict(poem_id=761,rationale='Keep the questions addressed to Time open; neither a clock nor an hourglass adds meaning.',status='pending')]
for p in (S/'content/editions/issue-43').glob('poem-*.json'):(B/p.name).write_bytes(p.read_bytes())
b=dict(edition=43,status='planned',created_at=now,poems_read=sorted(json.loads(p.read_text())['id'] for p in (S/'content/editions/issue-43').glob('poem-*.json')),direction='Keeping company: stored memory, a familiar landscape becoming uncertain, and midnight shadows as companionship. Three different visual densities and media; an interpretation selected for this rollout, not a claim about the original editorial theme.',items=items,text_led=plain,independent=False)
(B/'batch.json').write_text(json.dumps(b,ensure_ascii=False,indent=2)+'\n');ed=next(x for x in q['editions'] if x['edition']==43);ed.update(status='planned',artworks=[i['id'] for i in items],text_led=[i['poem_id'] for i in plain],batch=str((B/'batch.json').relative_to(R)),direction=b['direction']);q['active_batch']=dict(id='edition-43',owner='current-chat-assistant',started_at=now,status='running');q['updated_at']=now;(K/'queue.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
print('Edition43 planned; all15 source snapshots retained.')
