"""Record successful publication using saved live evidence; preserve each checkout's newer work."""
import json,sys
from pathlib import Path
from datetime import datetime,timezone
R=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else Path(__file__).resolve().parents[3];K=R/'kb/research/edition-art-rollout-2026-10-04';now=datetime.now(timezone.utc).isoformat()
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
v=json.loads((K/'checkpoint-41-39-live-verification.json').read_text());assert v['result']=='PASS';commit=v['commit'];workflow=v['workflow'];q=json.loads((K/'queue.json').read_text())
for n in [41,40,39]:
 p=K/f'batches/edition-{n}/batch.json';b=json.loads(p.read_text());assert b['status'] in ['verified_local_pending_publication','published_verified'];b.update(status='published_verified',publication=dict(commit=commit,workflow_id=workflow,verified_at=v['verified_at'],result='PASS'));b['checks']['publication']='Deployed and live verified: exact asset hashes, poem pages, noindex and engagement preserved';save(p,b)
 e=next(e for e in q['editions'] if e['edition']==n);e.update(status='published_verified',publication_commit=commit,publication_workflow=workflow)
q['counts'].update(published_editions=sum(e['status']=='published_verified' for e in q['editions']),verified_local_unpublished_editions=sum(e['status']=='verified_local_pending_publication' for e in q['editions']));q['updated_at']=now;save(K/'queue.json',q)
p=R/'kb/records/edition-art-rollout-2026-10-04.json';r=json.loads(p.read_text());r['counts']=q['counts'];r['current_publication'].update(status='deployed_and_live_verified',commit=commit,workflow_id=workflow,workflow_url=f'https://github.com/ahimanikya/kabita-live/actions/runs/{workflow}',verified_at=v['verified_at'],verification='research/edition-art-rollout-2026-10-04/checkpoint-41-39-live-verification.json');r['next_action']=f'Resume edition{q["next_edition"]}; publish the next three verified unpublished editions together. Editions39–47 are live.';save(p,r)
receipt=dict(recorded_at=now,status='deployed_and_live_verified',decision_ref='KBL-DEC-046',work_ref='KBL-WORK-022',editions=[41,40,39],artworks=9,text_led=9,commit=commit,workflow_id=workflow,workflow_url=f'https://github.com/ahimanikya/kabita-live/actions/runs/{workflow}',url='https://ahimanikya.github.io/kabita-live/',checks=dict(local='PASS2738 protected files including published portraits;781 unrelated pages unchanged;799 readers and payloads;26 app tests;10 rules tests in successful CI',live='PASS9 exact asset hashes;18 poem pages; active Firebase/Likes/comments/GA4 and noindex',visual='Desktop/mobile self-review for all3 editions; live poem706 image and loaded Like0/comments region verified without submitting engagement'),evidence='research/edition-art-rollout-2026-10-04/checkpoint-41-39-live-verification.json',independent=False)
save(R/'kb/records/edition-art-checkpoint-41-39-publication-2026-10-04.json',receipt)
p=R/'kb/registers/activity.jsonl';events=[json.loads(s) for s in p.read_text().splitlines() if s.strip()];eid=max(int(x['id'].split('-')[-1]) for x in events)+1
with p.open('a') as f:f.write(json.dumps(dict(id=f'KBL-EVT-{eid:03}',recorded_at=now,actor=dict(kind='ai_assistant',name='Current assistant; same-assistant release verification'),summary='Published and live-verified editions41/40/39:9 new poem-informed Human Natural / Poetic Natural illustrations and9 text-led openings. Total27 edition illustrations now live across9 editions. All9 exact asset hashes and18 pages pass; active engagement, consent/noindex settings, historical covers, poetry and remote portraits preserved. Desktop/mobile evidence and exact prompts retained; independent:false.',refs=['KBL-WORK-022','KBL-DEC-046'],evidence=['records/edition-art-checkpoint-41-39-publication-2026-10-04.json'],next_action=r['next_action']))+'\n')
print('Recorded successful publication',commit,'in',R)
