'use strict';
const data=JSON.parse(document.getElementById('review-data').textContent);
const test=new URLSearchParams(location.search).get('test')==='1';
const key='kabita-writer-audit-decisions-v1'+(test?'-test':'');
const $=id=>document.getElementById(id), labels={pending:'Not decided',approved:'Approved as written',edit:'Edit requested',rejected:'Added text rejected'};
let saved={}, storageOK=true, current=null, sessionModified=false;
try{const raw=JSON.parse(localStorage.getItem(key)||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))saved=raw;}catch{storageOK=false}
$('testbanner').hidden=!test;
function record(p){const d=saved[p.id]||(!test&&data.applied_decisions?.[p.id]);return d&&typeof d==='object'?d:{}}
function state(p){const d=record(p);return d.hash===p.hash&&['approved','edit','rejected'].includes(d.decision)?d.decision:'pending'}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function safeLink(label,url){const a=el('a',label);try{const u=new URL(url,'http://127.0.0.1:8771/');if(!['http:','https:'].includes(u.protocol))return el('span',label);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';a.title='Opens in a new tab'}catch{return el('span',label)}return a}
function button(text,fn,cls){const b=el('button',text,cls);b.type='button';b.onclick=fn;return b}
function persist(){try{localStorage.setItem(key,JSON.stringify(saved));storageOK=true}catch{storageOK=false}storageMessage()}
function storageMessage(){ $('storage').textContent=storageOK?'Saved in this browser only. Export decisions and share the file here to apply them.':'Browser saving unavailable. Keep this tab open and export decisions before leaving.'; }
function counts(){const c={pending:0,approved:0,edit:0,rejected:0};data.profiles.forEach(p=>c[state(p)]++);$('progress').replaceChildren(...Object.entries(c).map(([s,n])=>{const x=el('span');x.append(el('strong',String(n)),' '+labels[s]);return x}));}
function filtered(){const query=$('search').value.trim().toLocaleLowerCase();return data.profiles.filter(p=>($('group').value==='all'||($('group').value==='priority'?p.findings.length:p.flags.length))&&($('status').value==='all'||state(p)===$('status').value)&&(!query||(/^\d+$/.test(query)?p.id===query:(p.name+' '+p.id).toLocaleLowerCase().includes(query)))).sort((a,b)=>a.name.localeCompare(b.name));}
function queue(){const list=filtered();$('queue-count').textContent=list.length+' writers in this view';$('queue').replaceChildren(...list.map(p=>{const li=el('li');const b=button('',()=>select(p.id));b.setAttribute('aria-current',String(current===p.id));b.append(el('span',p.name,'name'),el('small','#'+p.id+' · '+labels[state(p)]));li.append(b);return li}));counts();return list;}
function select(id){current=id;const p=data.profiles.find(p=>p.id===id);if(!p)return;queue();render(p);const u=new URL(location.href);u.hash='writer-'+p.id;history.replaceState(null,'',u);}
function refresh(){const list=queue();if(!list.some(p=>p.id===current))current=list[0]?.id||null;queue();if(current)render(data.profiles.find(p=>p.id===current));else{$('profile').replaceChildren();$('empty').hidden=false;}}
function detail(title){const d=el('details');d.append(el('summary',title));return d}
function saveNote(p,value){const d=record(p);saved[p.id]={...d,hash:p.hash,decision:state(p),notes:value,updated_at:new Date().toISOString()};sessionModified=true;persist()}
function decide(p,decision){const notes=$('notes').value.trim();if(decision==='edit'&&!notes){$('message').textContent='Tell us what to change before requesting an edit.';$('notes').focus();return}saved[p.id]={hash:p.hash,decision,notes,updated_at:new Date().toISOString()};sessionModified=true;persist();queue();render(p);$('message').textContent=labels[decision]+'. '+(storageOK?'Saved in this browser.':'Export to keep this decision.');}
function render(p){$('empty').hidden=true;const root=$('profile');root.replaceChildren();const d=record(p),s=state(p);
 const top=el('div',undefined,'profile-top'),identity=el('div');identity.append(el('p','Writer '+p.id,'eyebrow'),el('h2',p.name),el('span',labels[s],'tag '+s));top.append(identity,safeLink('Open full profile ↗',p.route));root.append(top);
 if(d.hash&&d.hash!==p.hash)root.append(el('p','The writer text has changed since your saved decision. Please review again; your earlier notes are retained.','notice'));
 const concerns=el('section',undefined,'card');concerns.append(el('h3','What needs attention'));
 if(p.findings.length){p.findings.forEach(f=>{const c=el('div',undefined,'concern');if(f.status==='closed_corrected'){c.append(el('p',f.id+' · Closed — correction applied','scope'),el('h3',f.title),el('p',f.resolution?.change||'Approved correction applied to the poet page.'));concerns.append(c);return}c.append(el('p',f.id+' · '+(f.priority==='first'?'Review first':'Follow-up'),'scope'),el('h3',f.title),el('p',f.doubt));const action=el('p');action.append(el('strong','Suggested next step: '),f.recommended_action);c.append(action);if(f.writer_ids.length>1){const related=el('div');related.append(el('span','Related profiles: '));f.writer_ids.filter(i=>String(i)!==p.id).forEach(i=>{const other=data.profiles.find(x=>x.id===String(i));if(other)related.append(button(other.name,()=>{$('group').value='all';$('status').value='all';$('search').value='';select(other.id)}))});c.append(related)}concerns.append(c)})}
 const flagText={source_limited:'Limited source evidence: the added text relies on captured contributor material or poem interpretation.',all_recorded_sources_indexed_only:'All recorded external support was accessed through search/index text; no full source opening was recorded.',source_access_not_recorded:'Earlier research lacks a complete source-access record.'};p.flags.forEach(f=>concerns.append(el('p',flagText[f]||f,'hint')));
 if(!p.findings.length&&!p.flags.length)concerns.append(el('p','No specific issue was selected in the initial screening. This is not independent factual clearance.','hint'));
 root.append(concerns);
 const bio=el('section',undefined,'card');bio.append(el('p','Text you are reviewing','eyebrow'));const text=el('div',undefined,'reading');p.enrichment.sections.forEach(sec=>{text.append(el('h3',sec.heading));sec.paragraphs.forEach(par=>text.append(el('p',par)))});bio.append(text);if(p.enrichment.books.length){bio.append(el('h3','Added book entries'));const ul=el('ul',undefined,'books');p.enrichment.books.forEach(b=>{const li=el('li');li.append(safeLink(b.title,b.url),el('small',b.detail||''));ul.append(li)});bio.append(ul)}root.append(bio);
 const evidence=detail('Sources and research limitations');const list=el('ol',undefined,'sources-list');p.sources.forEach(src=>{const li=el('li',undefined,'source');li.append(safeLink(src.label||src.url,src.url));const supports=Array.isArray(src.supports)?src.supports.join(' '):(src.supports||'Claim-level support was not recorded.');li.append(el('p',supports),el('small','Access recorded: '+(src.access||'not recorded')));list.append(li)});evidence.append(p.sources.length?list:el('p','No identity-confirmed external source was recorded.'));const lim=el('ul',undefined,'limitations');p.limitations.forEach(l=>lim.append(el('li',l)));evidence.append(lim);root.append(evidence);
 const original=detail('Original contributor biography · preserved');original.append(el('p','Captured text is shown for comparison. It can contain older or unverified claims. Your decision here applies to the added text above.','hint'),el('p',p.original||'No biography is available in the directory capture. Consult the source dossier for any archived poem-page biography.','original'));root.append(original);
 const visual=detail('Preview the complete writer page');visual.addEventListener('toggle',()=>{if(visual.open&&!visual.querySelector('iframe')){const frame=el('iframe');frame.title='Full profile preview for '+p.name;frame.src=p.route;frame.loading='lazy';visual.append(frame)}});root.append(visual);
 const decision=el('section',undefined,'card decision');decision.append(el('h3','Your decision'),el('p','Approve keeps the added biography and book entries as written. Reject marks those additions for removal. Neither choice changes the original poems, portraits or captured biography.','hint'));
 const label=el('label','Notes or requested changes');label.htmlFor='notes';const notes=el('textarea');notes.id='notes';notes.maxLength=12000;notes.placeholder='What should be corrected, shortened, removed or checked?';notes.value=typeof d.notes==='string'?d.notes:'';notes.oninput=()=>saveNote(p,notes.value);decision.append(label,notes);
 const actions=el('div',undefined,'actions');[['approved','Approve as written'],['edit','Request edit'],['rejected','Reject added text']].forEach(([value,label])=>{const b=button(label,()=>decide(p,value),value==='approved'?'primary':'');b.setAttribute('aria-pressed',String(s===value));actions.append(b)});decision.append(actions,button('Return to undecided',()=>decide(p,'pending')));const msg=el('p','Decisions are review instructions; they do not publish or automatically change the site.');msg.id='message';msg.setAttribute('role','status');decision.append(msg);root.append(decision);
 const nav=el('div',undefined,'navigation'),visible=filtered(),index=visible.findIndex(x=>x.id===p.id);const previous=button('← Previous',()=>{if(index>0)select(visible[index-1].id)}),next=button('Next writer →',()=>{const target=index>=0?visible[index+1]:visible[0];if(target)select(target.id)});previous.disabled=index<=0;next.disabled=index>=visible.length-1&&index>=0||!visible.length;nav.append(previous,el('span',index>=0?(index+1)+' of '+visible.length+' in this view':'Saved. This writer no longer matches the selected filter.'),next);root.append(nav);
}
function packageDecisions(){return {schema_version:1,review:data.audit,exported_at:new Date().toISOString(),test_session:test,publication_authorized:false,decision_scope:'Added biography and book entries only. Decisions do not establish independent factual accuracy or authorize publication.',decisions:data.profiles.filter(p=>Object.keys(record(p)).length).map(p=>({writer_id:Number(p.id),name:p.name,reader_snapshot_sha256:record(p).hash,current_snapshot_sha256:p.hash,decision:state(p),previous_decision_if_stale:record(p).hash!==p.hash?record(p).decision:null,notes:record(p).notes||'',updated_at:record(p).updated_at||null,finding_ids:p.findings.map(f=>f.id)}))};}
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(packageDecisions(),null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=el('a');a.href=url;a.download='kabita-writer-audit-decisions'+(test?'-TEST':'')+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);sessionModified=false;$('storage').textContent='Export requested. Keep the downloaded file and share it here for implementation.'};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(packageDecisions(),null,2));$('storage').textContent='Decisions copied. Paste them in this chat when ready.'}catch{$('storage').textContent='Copy unavailable. Use Export decisions instead.'}};
$('search').oninput=refresh;$('group').onchange=refresh;$('status').onchange=refresh;
window.addEventListener('beforeunload',e=>{if(!storageOK&&sessionModified){e.preventDefault();e.returnValue=''}});
const initial=location.hash.match(/^#writer-(\d+)$/)?.[1];if(data.profiles.some(p=>p.id===initial)){current=initial;if(!filtered().some(p=>p.id===initial))$('group').value='all'}storageMessage();refresh();
