from pathlib import Path
import re,os,json
R=Path(__file__).resolve().parents[5];S=R/'projects/site';O=Path(__file__).parent;M=R/'kb/artifacts/design/icon-studies/footer-earth-voice-v2'
items=[('Our story','about.html','our-story','Palm-leaf manuscript'),('Send a poem','submit.html','send-poem','Stylus & new leaf'),('Contact','contact.html','contact','Letter & leaf seal'),('Facebook','https://www.facebook.com/profile.php?id=61594946730649','facebook','Familiar f & an ink circle')]
def mark(name):return (M/f'{name}.svg').read_text().replace('<svg ','<svg class="footer-icon" ',1)
links=[]
for label,url,key,story in items:
 extra=' target="_blank" rel="noopener noreferrer"' if url.startswith('https:') else ''
 name=label+(' (external link, opens in a new tab)' if extra else '')
 links.append(f'<a href="{url}" aria-label="{name}" title="{name}"{extra}>{mark(key)}<span class="footer-link-label">{label}</span></a>')
nav='<nav class="footer-links" aria-label="Footer">'+''.join(links)+'</nav>'
source=(S/'poem-8.html').read_text();text=re.sub(r'<nav class="footer-links" aria-label="Footer">.*?</nav>',lambda m:nav,source,flags=re.S);text=text.replace('<title>','<title>Footer icon study · ',1).replace('</head>','<style>.footer-icon{width:24px;height:24px}</style></head>');(O/'poem-footer-icon-mock.html').write_text(text)
cards=''.join(f'<figure class="icon-study">{mark(key)}<figcaption><strong>{label}</strong><span>{story}</span></figcaption></figure>' for label,url,key,story in items)
foot='<div class="footer-simple footer-sample"><div class="earth-edge" aria-hidden="true"></div><div class="footer-line"><p class="footer-credit">Poetry belongs to its respective authors.</p>'+nav+'</div></div>'
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Footer · Earth & voice</title><link rel="stylesheet" href="assets/style.css"><style>
body{padding:32px 24px}.icon-review{max-width:1100px;margin:auto}.review-head{display:flex;justify-content:space-between;gap:24px;align-items:center}.review-head h1{font:500 42px/1.2 var(--display)}.review-head button{min-height:44px;padding:8px 16px;border:1px solid var(--line);border-radius:3px;font:15px var(--ui)}.intro{margin:12px 0 28px;color:var(--muted);font:17px/1.6 var(--ui)}.studies{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;border-bottom:1px solid var(--line);padding-bottom:28px}.icon-study{margin:0;text-align:center}.icon-study .footer-icon{width:56px;height:56px;margin:4px auto 14px;display:block}.icon-study figcaption strong{font:500 18px/1.5 var(--ui);display:block}.icon-study figcaption span{font:14px/1.5 var(--ui);color:var(--muted)}.sample-title{font:600 25px/1.3 var(--display);margin:28px 0 12px}.footer-sample{margin-top:56px}.footer-sample .footer-icon{width:24px;height:24px}.phone-preview{width:360px;max-width:100%;padding:0 16px;margin:0 auto;border-inline:1px solid var(--line)}.phone-preview .footer-line{flex-direction:column;gap:8px}.phone-preview .footer-credit{font-size:13px;text-align:center;width:100%}.phone-preview .footer-links{margin:0;width:100%;justify-content:center;flex-wrap:nowrap;gap:16px}.phone-preview .footer-links a{width:44px;min-width:44px;height:44px;padding:8px}.phone-preview .footer-link-label{display:none}.phone-preview .earth-edge{width:125px;height:42px;top:-42px;background-size:310px auto}.review-link{display:inline-flex;align-items:center;min-height:44px;text-decoration:underline;text-underline-offset:4px;margin-top:16px;font:16px var(--ui)}@media(max-width:680px){body{padding:24px 16px}.studies{grid-template-columns:1fr 1fr;gap:28px 16px}.review-head h1{font-size:34px}.review-head{align-items:start}.desktop-preview .footer-links{gap:12px}.icon-study .footer-icon{width:48px;height:48px}}
</style></head><body class="journal-paper cotton-paper"><main class="icon-review"><header class="review-head"><h1>Small marks, from home.</h1><button id="theme-preview" aria-pressed="false">Preview dark</button></header><p class="intro">One ink colour. Gentle curves. A small trace of earth, leaf and written word.</p><section class="studies">'''+cards+'''</section><h2 class="sample-title">In the footer</h2><section class="desktop-preview">'''+foot+'''</section><h2 class="sample-title">On a phone</h2><section class="phone-preview">'''+foot+'''</section><a class="review-link" href="poem-footer-icon-mock.html#footer">See the full poem page</a></main><script>document.querySelector('#theme-preview').onclick=function(){const on=document.body.classList.toggle('night');this.setAttribute('aria-pressed',on);this.textContent=on?'Preview light':'Preview dark'};</script></body></html>'''
(O/'review.html').write_text(html)
for name,file in [('footer-icon-theme-review.html','review.html'),('poem-footer-icon-mock.html','poem-footer-icon-mock.html')]:
 link=S/name
 if not link.exists():link.symlink_to(os.path.relpath(O/file,S.resolve()))
manifest={'status':'candidate_awaiting_user_review','direction':'Single-colour Earth & voice','viewBox':'0 0 24 24','stroke':1.35,'display_size':24,'minimum_touch_target':44,'source':'Original SVG construction for this review; palm-leaf/stylus/leaf-seal forms are design interpretations, not historical artefact reproductions','icons':[{'id':key,'label':label,'motif':story,'file':key+'.svg'} for label,url,key,story in items]};(M/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Four original SVG candidates and two footer previews created')
