"""One-time, source-preserving setup for the approved three-edition pilot."""
import json, hashlib
from pathlib import Path
from datetime import datetime, timezone
R=Path(__file__).resolve().parents[3]
K=R/'kb/research/edition-art-pilot-2026-10-04'
A=R/'kb/artifacts/artwork/edition-art-pilot-2026-10-04'
S=R/'projects/site'
now=datetime.now(timezone.utc).isoformat()
def save(p,d): p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
if (K/'queue.json').exists(): raise SystemExit('Existing pilot: resume, never recreate.')
A.mkdir(parents=True,exist_ok=True)
poems={json.loads(p.read_text())['id']:(p,json.loads(p.read_text())) for p in (S/'content/editions').glob('*/poem-*.json')}
assign=json.loads((S/'data/poem-art-assignments.json').read_text())['assignments']
specs=[
 (47,812,'threshold-memory','A meal at the doorway','A steel meal plate just inside an ordinary shaded room, seen from floor height across a red-earth-coloured threshold. The adjacent courtyard is mostly outside the crop. A simple cotton curtain hangs naturally to one side. No bridal decorations. Warm quiet daylight, restrained laterite and ivory washes with grey-green shadow. The meal arriving at a sulking child is remembered by a mother preparing for her daughter’s departure; suggest care without depicting identifiable people.','A domestic threshold and meal recall maternal care without inventing a portrait or wedding scene.'),
 (47,822,'oleander-walkway','Morning along the path','An oblique close view along the edge of a modest sunlit walkway. A naturally growing yellow oleander branch enters from the upper side, narrow overlapping leaves and a few yellow funnel flowers, one partly hidden. A broad unremarkable section of path and its interrupted leaf shadow remain open. No decorative scattered flowers, honey pouring or literal musical symbols. Slightly dry brush outlines only near two flowers; softer pale grey-green and laterite washes toward the edge.','Close botanical observation answers the poem’s attentive morning without illustrating every metaphor.'),
 (47,823,'breath-in-bamboo','A place for breath','A spare close crop of a plain transverse bamboo flute lying diagonally on a simple cotton cloth on a low unpainted ledge near an open window. The flute has one separate blowing hole and a plausible straight run of six finger holes; one end may leave the crop. Empty air and pale ivory space dominate. Bamboo ochre, warm grey, very restrained green shadow. No decorative tassels, deity symbols, smoke, floating notes or people. Light falls from the window with a small grounded contact shadow.','The material flute suggests breath becoming music, leaving the poem’s intimacy to the words.'),
 (46,792,'room-for-a-tree','Room for a tree','A small healthy leafy fruit-tree sapling in a plain terracotta pot at the edge of a narrow paved yard. Most of the view is the unplanted paving beyond it, with a modest strip of actual soil visible at the far edge. Rooted stems and irregular overlapping leaves; no fruit display, decorative birds or garden paradise. Muted mineral green, terracotta and paper cream, matte gouache and open watercolor.','The confined sapling embodies the search for ground; avoid inventing a precise botanical identification.'),
 (46,789,'pondside-warmth','Pondside warmth','An ordinary small brown lizard rests low on a sun-warmed rough stone beside pond water, seen close from near bank level. It is not facing the viewer; part of its tail recedes behind the stone. Plausible four-limbed anatomy. Quiet olive-brown pond wash and an uneven edge of reeds are subordinate. Selective fine brush near head and foreleg; broad matte green and warm mineral washes elsewhere. No other haiku nouns or fantasy animals.','Choose one small lived observation from the sequence, keeping the haiku’s changes of scale open.'),
 (46,788,'mind-orbits','What reaches the page','A nonliteral abstract watercolor study of a few uneven overlapping translucent circular arcs, mineral blue-grey and muted burnt sienna on broad unpainted ivory paper. One partial arc leaves the frame; a very small warm mark sits away from the densest crossing. Let water blooms and pigment mixing follow actual wet paper. No astronomical diagram, starscape, glitter, text, symbols, human head, eyeball or symmetrical mandala.','An abstract pause for inner galaxies; it must be visibly a painting, not fabricated astronomy.'),
 (45,774,'two-petals','Words, almost','An intimate oblique view of two small pale flower petals, unequal and partly overlapping, caught at an ordinary stone sill. One edge curls naturally; most of the plane is empty cool grey-blue wash. Restrained warm ochre at a small surface joint. No whole flowers, decorative dew or written page. Watercolor on ivory paper, loose dry edges, focus only at their contact.','Two petals echo the closing intimacy without repeating an entire courtyard or arranging a floral emblem.'),
 (45,782,'shutter-morning','Before the day separates us','A cropped street-level view of a small neighbourhood tea shop as its rolling shutter is partly raised. A plain tea glass rests near the inner counter edge; the front of a parked bicycle is cut by the side of the frame. No people, logos or readable signage. Ordinary pale morning light, quiet cool slate-blue shadows with a little warm ochre. Perspective and shutter slats coherent, background interior simple and dim rather than picturesque. Loose watercolor with a few pencil-like structural marks.','An everyday shop beginning its day connects public morning sounds with private separation.'),
 (45,785,'city-at-night','The city keeps its quiet','A modest view from a domestic balcony across a few ordinary low rooftops at night. Cropped parapet in the near corner; one distant warm window, mostly quiet dark blue-grey roof planes and open sky. No skyline landmark, glittering galaxy, moon spectacle, rain overlay or dramatic figure. Evening watercolor washes, selective rough pencil structure, restrained ochre light whose glow reaches only nearby surfaces.','The outer city remains calm while the poem carries its inward argument; no biographical setting is claimed.')]
items=[]
for ed,pid,ident,title,scene,reason in specs:
 p,d=poems[pid]
 evidence=K/f'poem-{pid}.json'; evidence.write_bytes(p.read_bytes())
 prompt=('Use case: illustration-story. Create one original horizontal 3:2 interior illustration for Kabita Live, edition '+str(ed)+'. Human Natural / Poetic Natural literary art, visibly painted rather than a photograph. Emotional anchor: '+reason+'\nScene and composition: '+scene+'\nPurpose: accompany '+d['title']+' by '+d['author']+'. A new visual interpretation, not a documentary record or the author’s stated intention. Preserve breathing room and believable materials. Keep beauty without optimizing every surface. No uniform microdetail, digital HDR, forced grain, gratuitous grime, cinematic rays, ornamental border, words, signature or watermark. Soft varied watercolor edges within the rectangular cream-paper image; opaque background.\nPoem read as context (do not render this text):\n'+d['text'])
 prompt_path=K/f'{ident}-prompt.txt';prompt_path.write_text(prompt+'\n')
 items.append(dict(id=ident,edition=ed,poem_id=pid,title=title,status='pending',batch=f'edition-{ed}',rationale=reason,poem_source=str(p.relative_to(R)),poem_sha256=sha(p),poem_evidence=str(evidence.relative_to(R)),prompt=str(prompt_path.relative_to(R)),previous_assignment=assign.get(str(pid)),output=f'kb/artifacts/artwork/edition-art-pilot-2026-10-04/{ident}/v1.png',independent=False,attempts=[]))
text_led={775:'Let the riddle and unanswered questions carry the tension.',778:'The poem asks not to equate a poet with a pictured character; give its argument space.',783:'A very short poem benefits from an unillustrated pause.',794:'Avoid decorative imagery for the poem’s political violence and ethical anger.',795:'Keep the address and emotional language open rather than inventing a couple.',800:'Do not aestheticize withdrawal or illustrate an assumed diagnosis.',819:'Keep this declaration of autonomy free of the generic bird-and-cage shorthand.',821:'Let the named ordinary memories remain the reader’s own, without another writing-desk image.'}
for pid in text_led:
 p,d=poems[pid];(K/f'poem-{pid}.json').write_bytes(p.read_bytes())
save(K/'queue.json',dict(schema_version=1,created_at=now,updated_at=now,status='in_progress',batch_size=3,batch_order=[47,46,45],next_id=items[0]['id'],active_batch=None,counts={'pending':9,'verified':0,'held':0},items=items,text_led=[dict(poem_id=pid,edition=poems[pid][1]['edition'],rationale=reason,status='pending') for pid,reason in text_led.items()]))
save(K/'baseline.json',dict(created_at=now,assignments=assign,poem_files={str(p.relative_to(R)):sha(p) for p,d in poems.values()},cover_files={str(p.relative_to(R)):sha(p) for p in (S/'assets/covers').rglob('*') if p.is_file()},variants={p.name:{k:v['stanzas'] for k,v in json.loads(p.read_text()).get('variants',{}).items()} for p in []}))
record=dict(recorded_at=now,status='in_progress',work_ref='KBL-WORK-021',decision_ref='KBL-DEC-045',authorization=['Sounds good, let’s do that','Do that in batched and keep a loop'],scope='Three-edition local pilot: 45,46,47; nine new interior artworks in three sequential edition batches; eight explicit text-led poem openings. Covers, poems, existing bespoke art and other editions preserved. No publication.',automation_id='kabita-live-poetic-natural-artwork',queue='research/edition-art-pilot-2026-10-04/queue.json',gallery='artifacts/artwork/edition-art-pilot-2026-10-04/index.html',independent=False,edition_directions={'47':'Ordinary closeness: laterite, pale green and ivory; domestic threshold, botanical observation, a spare material study.','46':'Small life and inward space: mineral greens, earth and blue; close observation, confined growth and one abstract pause.','45':'Between day and night: cool slate washes with restrained ochre; intimate petals, a street beginning, an inwardly quiet city.'},direction_note='New visual direction inferred from selected poems; not a claim about historical editorial themes.',preserved_bespoke_poems=[809,810,814,786],next_action='Generate and review edition47, integrate locally, verify reading controls and content hashes, then continue46 and45.',checks={})
save(R/'kb/records/edition-art-pilot-2026-10-04.json',record)
regpath=R/'kb/registers/records.json';reg=json.loads(regpath.read_text())
assert not any(d['id']=='KBL-DEC-045' for d in reg['decisions'])
reg['decisions'].append(dict(id='KBL-DEC-045',title='Edition-specific imagery pilot in an autonomous batch loop',status='approved',actor={'kind':'human','name':'Ahimanikya Satapathy'},quote='Sounds good, let’s do that. Do that in batched and keep a loop',scope=record['scope']+' No per-image or per-batch approval gate. Stop after the bounded pilot.',evidence=['records/edition-art-pilot-2026-10-04.json']))
reg['work'].append(dict(id='KBL-WORK-021',title='Edition-specific interior artwork pilot',status='in_progress',readiness='draft',human_owner='Ahimanikya Satapathy',authorization='KBL-DEC-045',next_action=record['next_action'],blockers=[],refs=['KBL-WORK-004'],evidence=['records/edition-art-pilot-2026-10-04.json','research/edition-art-pilot-2026-10-04/queue.json']))
save(regpath,reg)
print('Created nine-image queue and source/hash baseline; no site changes.')
