from pathlib import Path
import os
OUT=Path(__file__).parent;ROOT=OUT.resolve().parents[3];SITE=ROOT/'projects/site'
icon=(SITE/'assets/icons/earth-voice-v1/ink/boita.svg').read_text().replace('role="img" aria-label="A small boat, a long memory"','aria-hidden="true"')
sample=(OUT/'footer-signature-a.html').read_text()
row='<div class="reference-art" aria-hidden="true"><div class="reference-lotus"></div><div class="reference-boita">'+icon+'</div><div class="reference-boat"></div></div>'
sample=sample.replace('<div class="boat" aria-hidden="true"></div>',row)
sample=sample.replace('</style>','''
.sample{max-width:1100px;margin:0 auto}.sample-end{display:none}.reference-art{display:grid;grid-template-columns:minmax(0,1fr) 96px minmax(0,1fr);align-items:end;gap:32px;padding:24px 0 18px}.reference-lotus,.reference-boat{height:120px;width:100%;max-width:300px;background-image:url(assets/odisha-watercolour.webp);background-repeat:no-repeat;background-size:840px auto;opacity:.9}.reference-lotus{background-position:left bottom}.reference-boat{background-position:right bottom;justify-self:end}.reference-boita{color:var(--rust);display:flex;justify-content:center}.reference-boita svg{width:88px;height:88px}.signature-line{padding:12px 0}@media(max-width:600px){.sample{padding:12px 16px 0}.reference-art{grid-template-columns:minmax(0,1fr) 46px minmax(0,1fr);gap:12px;padding:12px 0 14px}.reference-lotus,.reference-boat{height:54px;background-size:340px auto}.reference-boita svg{width:44px;height:44px}.signature-line{padding:8px 0}}
</style>''')
(OUT/'footer-reference-sample.html').write_text(sample)
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Your footer reference · Preview</title><link rel="stylesheet" href="assets/style.css"><style>body{padding:0 0 30px!important}.reference-desk{max-width:1140px;margin:auto;padding:24px}.reference-desk h1{font:500 42px/1.1 'Cormorant Garamond';margin:12px 0}.reference-desk p{font:16px/1.6 var(--serif);color:var(--muted);max-width:750px}.reference-desk h2{font:12px/1.5 var(--ui);text-transform:uppercase;letter-spacing:.12em;margin:28px 0 12px}.reference-desk iframe{display:block;width:100%;height:275px;border:1px solid var(--line)}.phone{max-width:390px;border:5px solid var(--ink);border-radius:20px;overflow:hidden}.phone iframe{height:220px;border:0}.reference-desk a{text-decoration:underline;text-underline-offset:3px}.reference-desk .note{font:12px/1.5 var(--ui)}@media(max-width:600px){.reference-desk{padding:20px}.desktop-sample{display:none}.reference-desk h1{font-size:36px}}</style></head><body class="journal-paper"><main class="reference-desk"><span class="eyebrow">FOOTER · REFERENCE PREVIEW</span><h1>As in your image.</h1><p>The lotus on the left, the terracotta boat in the centre, and the watercolor boat on the right—using our existing artwork and artistic icons.</p><section class="desktop-sample"><h2>Desktop</h2><iframe title="Reference arrangement desktop" src="footer-reference-sample.html"></iframe></section><section><h2>Mobile</h2><div class="phone"><iframe title="Reference arrangement mobile" src="footer-reference-sample.html"></iframe></div></section><p class="note">Preview only. Existing pages are unchanged. <a href="footer-signature-mock.html">Compare the simpler alternatives</a>.</p></main></body></html>'''
(OUT/'footer-reference-mock.html').write_text(page)
for name in ['footer-reference-sample.html','footer-reference-mock.html']:
 p=SITE/name
 if not p.exists():p.symlink_to(os.path.relpath(OUT/name,p.parent.resolve()))
print('Reference footer preview ready.')
