from pathlib import Path
import re,os
ROOT=Path(__file__).resolve().parents[4];SITE=ROOT/'projects/site';OUT=Path(__file__).parent
html=(SITE/'archive.html').read_text()
nav=re.search(r'<nav class="footer-links".*?</nav>',html,re.S).group(0)
style='''
body{padding:0!important} .sample{padding:24px 26px 8px;min-height:200px}.sample-end{font:14px var(--ui);color:var(--muted);margin:0 0 22px}.sample-end a{text-decoration:underline;text-underline-offset:4px}.signature-footer{margin:0;padding:0;position:relative}.boat{pointer-events:none;width:190px;height:64px;margin:0 0 8px auto;background:url(assets/odisha-watercolour.webp) right bottom/510px auto no-repeat;opacity:.8}.signature-line{border-top:1px solid var(--line);padding:10px 0;display:flex;gap:12px;align-items:center;justify-content:space-between}.signature-line p{margin:0;font:12px/1.6 var(--ui);color:var(--muted)}.footer-links{display:flex;gap:20px;align-items:center}.footer-links a{display:inline-flex;align-items:center;gap:7px;min-height:44px;font:14px var(--ui)}.footer-icon{width:24px;height:24px}.footer-links .external-mark{display:none}.variant-b .boat{width:140px;height:48px;background-size:375px auto;margin:0 0 4px auto}.variant-b .signature-line{padding:6px 0}.quiet{padding:32px 28px 16px}.quiet p{font:20px/1.7 var(--serif);margin:0 0 32px}.quiet-nav{display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line);padding-top:12px;font:12px var(--ui);color:var(--muted)}.quiet-nav button{width:44px;height:44px;font-size:22px}.quiet-label{font:11px var(--ui);letter-spacing:.1em;color:var(--muted);margin-bottom:16px}
@media(max-width:600px){.sample{padding:16px 20px 0}.sample-end{font-size:12px;margin-bottom:16px}.boat{width:145px;height:50px;background-size:390px auto;margin-bottom:4px}.signature-line{flex-direction:column;gap:2px;padding:8px 0}.signature-line p{text-align:center;font-size:11px}.footer-links{gap:14px}.footer-links a{width:44px;justify-content:center}.footer-link-label,.external-mark{display:none}.variant-b .boat{width:100px;height:34px;background-size:270px auto;margin-bottom:3px}.variant-b .signature-line{padding:6px 0}}
'''
def shell(body):return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Footer signature preview</title><link rel="stylesheet" href="assets/style.css"><style>'+style+'</style></head><body class="journal-paper">'+body+'</body></html>'
for variant in ['a','b']:
 body=f'<div class="sample variant-{variant}"><p class="sample-end">End of page · <a href="poems.html" target="_top">Return to the poems</a></p><footer class="signature-footer"><div class="boat" aria-hidden="true"></div><div class="signature-line"><p>Poetry belongs to its respective authors.</p>'+nav+'</div></footer></div>'
 (OUT/f'footer-signature-{variant}.html').write_text(shell(body))
# Illustrative reader ending, not a proposed new poem or publication content.
(OUT/'footer-signature-quiet.html').write_text(shell('<div class="quiet"><div class="quiet-label">QUIET READING · ENDING PREVIEW</div><p>A reading space with room to breathe.</p><div class="quiet-nav"><button aria-label="Previous page" disabled>←</button><span>End of poem</span><button aria-label="Next page" disabled>→</button></div></div>'))
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>A quieter footer · Design preview</title><link rel="stylesheet" href="assets/style.css"><style>
body{padding:0 0 40px!important}.desk{max-width:1160px;margin:auto;padding:28px 24px}.desk h1{font:500 clamp(36px,5vw,52px)/1.15 var(--display,'Cormorant Garamond');margin:12px 0}.intro{max-width:700px;font:18px/1.65 var(--serif);color:var(--muted)}.choice{display:flex;flex-wrap:wrap;gap:8px;margin:24px 0 16px}.choice button{padding:12px 18px;min-height:44px;border:1px solid var(--line);font:14px var(--ui)}.choice button[aria-pressed=true]{background:var(--ink);color:var(--paper)}.option-note{font:15px/1.6 var(--ui);color:var(--muted);min-height:48px}.frames{display:grid;grid-template-columns:minmax(0,1fr) 360px;gap:28px;align-items:start}.frame-label{font:11px var(--ui);letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin:0 0 10px}iframe{width:100%;display:block;border:1px solid var(--line);height:250px;background:var(--paper)}.phone{width:360px;max-width:100%;border-radius:20px;overflow:hidden;border:6px solid var(--ink)}.phone iframe{height:250px;border:0}.desktop{grid-column:1/-1}.mobile{max-width:360px}.quiet-example{max-width:500px}.quiet-example iframe{height:220px}.review-caption{font:13px/1.6 var(--ui);color:var(--muted);margin-top:24px}.eyebrow{font:11px var(--ui);letter-spacing:.12em;color:var(--rust)}@media(max-width:700px){.desk{padding:20px}.frames{display:block}.desktop{display:none}.mobile,.quiet-example{margin-top:24px}.phone{width:100%}.option-note{min-height:72px}}
</style></head><body class="journal-paper"><main class="desk"><span class="eyebrow">LOCAL DESIGN PREVIEW</span><h1>A quieter ending.</h1><p class="intro">One watercolor boat. A little breathing room. The same artistic menu icons, with no lotus or central boat symbol.</p><div class="choice" role="group" aria-label="Footer treatment"><button aria-pressed="true" data-variant="a">A · Gentle signature</button><button aria-pressed="false" data-variant="b">B · Smallest footprint</button></div><p class="option-note" id="option-note">Recommended: a small, recognizable boat above the rule, with a compact menu beneath.</p><div class="frames"><section class="desktop"><p class="frame-label">Desktop · Actual footer spacing</p><iframe title="Desktop footer preview" data-footer src="footer-signature-a.html"></iframe></section><section class="mobile"><p class="frame-label">Mobile · Icons only</p><div class="phone"><iframe title="Mobile footer preview" data-footer src="footer-signature-a.html"></iframe></div></section><section class="quiet-example"><p class="frame-label">Quiet reading · Same for either option</p><iframe title="Quiet reading ending without decoration" src="footer-signature-quiet.html"></iframe><p class="review-caption">Illustrative ending only. Quiet reading keeps page controls and omits the website footer and artwork.</p></section></div><p class="review-caption">Preview only. Existing pages and artwork files are unchanged. The space around these preview frames is not part of the proposed footer.</p></main><script>document.querySelectorAll('[data-variant]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-variant]').forEach(x=>x.setAttribute('aria-pressed',x===b));document.querySelectorAll('[data-footer]').forEach(f=>f.src='footer-signature-'+b.dataset.variant+'.html');document.querySelector('#option-note').textContent=b.dataset.variant==='a'?'Recommended: a small, recognizable boat above the rule, with a compact menu beneath.':'A smaller boat and tighter spacing. Takes less room, but the watercolor detail is subtler.'}));</script></body></html>'''
(OUT/'footer-signature-mock.html').write_text(page)
for filename in ['footer-signature-mock.html','footer-signature-a.html','footer-signature-b.html','footer-signature-quiet.html']:
 p=SITE/filename
 if not p.exists():p.symlink_to(os.path.relpath(OUT/filename,p.parent.resolve()))
print('Footer comparison ready; reader files unchanged.')
