"""Reproduce evidence screening; curated findings are review questions, not error verdicts."""
import csv, hashlib, json
from pathlib import Path
from datetime import datetime, timezone
ROOT=Path(__file__).resolve().parents[4]
OUT=Path(__file__).parent
E=json.loads((ROOT/'projects/site/data/writer-enrichment.json').read_text())
D={int(p.stem):json.loads(p.read_text()) for p in (ROOT/'kb/research/writers/enrichment').glob('*.json')}
profiles=json.loads((ROOT/'projects/site/data/writer-profiles.json').read_text())
names={int(p['id']):p['name'] for p in profiles}
def name(i): return D[i].get('name',names.get(i,str(i)))
def paragraphs(i): return [p for s in E[str(i)].get('sections',[]) for p in s.get('paragraphs',[])]
def excerpt(i,contains):
    matches=[p for p in paragraphs(i) if contains in p]
    assert matches,(i,contains)
    return matches[0]
def sources(ids): return [{'writer_id':i, 'dossier':f'kb/research/writers/enrichment/{i}.json','sources':D[i]['sources']} for i in ids]
F=[]
def flag(ids,priority,kind,title,scope,claim,why,action,web=[]):
    F.append(dict(id=f'KBL-WA-{len(F)+1:03}',writer_ids=ids,names=[name(i) for i in ids],priority=priority,category=kind,title=title,status='open',scope=scope,exact_reader_text=claim,doubt=why,recommended_action=action,evidence=sources(ids),fresh_checks=web,independent=False))
flag([192,224],'first','identity','Neelam Saxena Chandra — two records','profile identity',[], 'The two dossiers identify the same bilingual writer and deliberately share a biography and book cards. The total 427 counts profile records, not 427 verified distinct people.', 'Confirm one identity and preferred canonical profile; reconcile poem ownership and redirects before any merge.')
flag([256,366],'first','identity','Neha Bhandarkar — two records','profile identity',[], 'Distinctive language/translation history and the same source/book evidence are reused across both records. Separate profile identity has not been justified.', 'Confirm duplicate identity with editor and map both sets of contributions before proposing a merge.')
flag([255,449],'first','identity_and_date','Tulika — probable duplicate and inconsistent award-date caution','active reader claim + profile identity',[excerpt(449,'2021 Pen')], 'Dossier255 flags captured2020 versus universityJanuary2021 and omits the date; profile449 states2021. Both depend on the same faculty page. A manuscript award cycle and presentation date might differ, but that has not been established.', 'Confirm both names refer to the same writer; obtain organizer record or explicitly attribute the date to the university consistently. Do not convert a manuscript into a published book.', ['Amity faculty page failed direct access (502); indexed university text again states January2021. This supports the attributed wording but does not reconcile the captured2020 record.'])
flag([342,410],'first','identity','Reema / Rima Sinha — probable duplicate, incomplete identity bridge','active reader claim + profile identity',[excerpt(410,'Sahitya Rachana')], 'Profile410 connects an external Hindi byline using name, language and Lucknow, without an exact-work match. It may duplicate342, whose founder affiliation provides a stronger identity anchor.', 'Confirm identity and preferred spelling; until then treat external publication attribution for410 as provisional. Do not copy credentials between the profiles.')
flag([142],'first','name','Nisith Raj / Nitish Raj','reader heading versus biography',[excerpt(142,'Nitish Raj')], 'Captured heading says Nisith while captured biography and institutional literary programme say Nitish. The affiliations support a probable spelling error, not authority to silently rename.', 'Confirm display spelling; preserve original captured heading in provenance.', ['NIT Jalandhar programme reopened: January2024 course; Nitish Raj, Literia Insight and Love in Modern Times appear on page2.'])
flag([177],'first','name','Soumen Ray / Soumen Roy','reader heading versus bibliography',[excerpt(177,'Soumen Roy')], 'Captured heading uses Ray, while supplied biography, book metadata and review use Roy. Evidence is indexed; preferred byline remains unresolved.', 'Confirm preferred byline against an author or publisher record and retain spelling history.')
flag([106],'first','name','Mandakini Bhattacharjee / Bhattacherya','reader heading versus institutional spelling',[excerpt(106,'Bhattacherya')], 'The institutional and publication spelling differs from the captured heading. Shared bibliography makes a match plausible; spelling still needs confirmation.', 'Confirm preferred display spelling. Do not infer that the teaching affiliation is false.', ['Fresh college index at /UG/TeacherData?id=183 and college CV uses Bhattacherya and documents teaching; direct page open still failed.'])
flag([408],'first','identity_and_evidence','Padmashree R.P. / Padmashree Niranjan','active reader identity and profession',[excerpt(408,'teacher trainer')], 'Dossier leaves alternate surname Niranjan unresolved. The sole external support is an indexed LinkedIn self-description matched through initials, city and occupation; reader prose asserts the identity and profession directly.', 'Confirm name bridge and professional description; meanwhile prefer explicit attribution to the supplied contributor note rather than implying independent verification.')
flag([423],'follow-up','identity','Youngbo Ma — unresolved spelling and poem provenance','contained limitation; no imported external biography',[excerpt(423,'contributor note')], 'Possible Ma Yongbo/Yongbo Ma match remains unconfirmed. Chinese original and translator credit for poem644 have not been located. The current modest attributed biography avoids importing that other record.', 'Confirm preferred Chinese/Roman name, exact poem provenance and translator before adding outside biography or books. Do not treat this as a proven misidentification.')
flag([404],'follow-up','identity_and_evidence','Pallabi Das — event attribution rests on regional matching','active reader claim',[excerpt(404,'February 2024')], 'Name, Odia poetry and Junagarh/Kalahandi connect a local event report to this contributor, but there is no exact poem or author confirmation. The event link is plausible rather than securely established.', 'Confirm the event participant is this writer; otherwise keep only the attributed local contributor facts.')
flag([49],'first','overstatement','Sujit Kumar Satapathy — invitation treated as attendance','active reader wording',[excerpt(49,'took part')], 'The cited Akademi document is an invitation listing scheduled readers. It supports being announced on the programme, not proof he actually attended. This is a concrete evidence-to-wording overstatement, not proof of nonattendance.', 'Use “was listed for a poetry reading” unless a post-event report verifies attendance.', ['Fresh official indexed invitation confirms the schedule and name; direct PDF retrieval failed.'])
flag([40],'follow-up','bibliography','Sujata Dash — four-book list and book cards','active reader bibliography',[excerpt(40,'four poetry')], 'The list and cards rely on a dated contributor biography, accessed through an index. No edition/ISBN confirmation was recorded for the newer titles. Attribution is transparent, but these are not independently catalogued book records.', 'Check Authorspress/catalogue records for Eternal Rhythm and Humming Serenades; confirm solo collection versus anthology role and edition details before calling the shelf verified.')
flag([195],'follow-up','bibliography','Tandra Mishra — Oh Father!','active reader bibliography',[excerpt(195,'Oh Father!')], 'The first-collection claim is attributed to a contributor biography. No publisher/library record was established; attribution reduces overstatement but does not establish publication.', 'Confirm title, authorship and publication from publisher/title page; otherwise retain only clearly attributed wording and no book card.')
flag([236],'follow-up','self_report','Divya Vats — professional credentials are self-described','active reader profession, already attributed',[excerpt(236,'professional profile')], 'The sources are two indexed LinkedIn items from the same person, not independent checks. The prose correctly attributes roles; the source_checked label must not be read as credential verification.', 'Verify identity and preferred professional wording with author/editor if retained; do not add clinical qualifications or efficacy claims.')
flag([218],'follow-up','bibliography_identity','Zakir Khan — Nandan Kaanan book attribution','book card',[b for b in E['218']['books'] if b['title']=='Nandan Kaanan'], 'Official catalogue identifies title, author name, publisher and2006 edition, but the link from this book-author entry to the particular journalist/poet remains contextual. No full title page or author bibliography was read.', 'Confirm this writer’s bibliography with publisher/title page. Avoid importing material about the comedian namesake.', ['Fresh official indexed catalogue row331 corroborates title, name, publisher and2006; it does not itself supply a biographical identity bridge.'])
flag([318],'follow-up','freshness_and_source_structure','Ranu Uniyal — affiliation freshness and poem boundary','active reader tense + interpretation basis',[excerpt(318,'teaches English')], 'Present-tense teaching rests on an undated author page and university CV. Both support the affiliation, but do not establish currency explicitly. Poem390 also contains a second contrasting block that may be separately titled; interpretation should not conceal this source uncertainty.', 'Use source-attributed affiliation if a current appointment is not checked; ask editor to reconcile poem390 boundary before expanding interpretation.', ['Author biography and university CV reopened; affiliation and named collections supported. CV records former head2019–2022; author site has template/date defects. Current retirement status was not established.'])
flag([429],'follow-up','source_structure','Bharati Hazarika — duplicated source behind interpretation','underlying poem; no proven biography error',[excerpt(429,'Glacier')], 'Poem699 contains a repeated full Glacier block and embedded title/byline. Close reading cannot count this repetition as deliberate poetic structure. The source’s scientific assertions are not independent biographical facts.', 'Reconcile the captured poem with its original publication/editor; keep interpretation restricted to textual themes and do not rewrite the preserved source automatically.')
flag([382,389],'follow-up','contribution_mapping','Gopikrishnan Kottoor and Gayatri Das — no linked local poems','profile completeness',[], 'Both dossiers record no linked current catalogue contributions. Kottoor’s literary discussion relies on publisher description; Gayatri Das has only an attributed short note. Processing these records does not make them fully corroborated contributor biographies.', 'Confirm contributor-to-poem mapping or editorial reason for retaining each profile; keep publisher summary distinct from close reading.')
flag([82,257,337],'follow-up','audit_trail','Three earlier profiles have thinner audit records','evidence-record completeness',[], 'These legacy dossiers lack source-access modes, claim-level support, identity_match and saved reader_draft fields used later. Existing links may support the prose, but this audit cannot classify their access method or independently reconstruct the earlier checks.', 'Backfill evidence for Narmada Nilotpala, Majrooh Rashid and Sabita Singh Meera before marking factual review complete; do not label the claims false or call them index-only.')
flag([438],'follow-up','interpretation','Zahir Hossain Baidya — broad literary characterization','active reader interpretation',[excerpt(438,'rooted in the intensity')], 'The opening sentence generalizes about a writing practice from a very small sample. It is assistant interpretation, not a sourced biographical fact. The dated college byline is more concrete and should remain separate.', 'Consider removing the broad opening and shortening the poem commentary. Apply this editorial test to other inferred style/theme paragraphs; it is not a factual error verdict.')

manual_ids=sorted({i for f in F for i in f['writer_ids']})
rows=[]
for i,d in sorted(D.items()):
    ss=d.get('sources',[]); has_access=bool(ss) and all(s.get('access') for s in ss)
    opened=any('opened' in str(s.get('access','')).lower() for s in ss)
    index_only=has_access and not opened
    issues=[]
    if d['status']=='source_limited_local_draft': issues.append('source_limited')
    if index_only: issues.append('all_recorded_sources_indexed_only')
    if ss and not has_access: issues.append('source_access_not_recorded')
    ids=[f['id'] for f in F if i in f['writer_ids']]
    text=' '.join(paragraphs(i))
    rows.append(dict(writer_id=i,name=name(i),existing_status=d['status'],screening_flags=issues,curated_findings=ids,independent_factual_review='pending',coverage='metadata/evidence screening; see curated findings for manual assessment',narrative_words=len(text.split()),book_cards=len(E[str(i)].get('books',[])),source_count=len(ss),recorded_opened_source=opened,all_sources_index_only=index_only,dossier=f'kb/research/writers/enrichment/{i}.json',limitations=d.get('limitations',[]),source_access=[{'url':s.get('url'),'access':s.get('access','not_recorded')} for s in ss]))
counts=dict(profiles=len(rows),source_limited=sum('source_limited' in r['screening_flags'] for r in rows),all_sources_index_only=sum(r['all_sources_index_only'] for r in rows),missing_access=sum('source_access_not_recorded' in r['screening_flags'] for r in rows),evidence_followup_unique=sum(bool(r['screening_flags']) for r in rows),curated_findings=len(F),curated_profiles=len(manual_ids),narrative_words=sum(r['narrative_words'] for r in rows),book_cards=sum(r['book_cards'] for r in rows))
report=dict(audited_at=datetime.now(timezone.utc).isoformat(),scope='All427 records screened for evidence metadata; targeted manual claim review and selected primary-source rechecks. Not a fresh line-by-line external verification of all biographies or215book cards.',independent=False,public_content_changed=False,counts=counts,findings=F,profiles=rows)
(OUT/'findings.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
with (OUT/'profile-screening.csv').open('w') as fh:
    w=csv.writer(fh);w.writerow(['Writer ID','Name','Existing classification','Evidence follow-up','Specific findings','Independent factual review','Words','Book cards'])
    for r in rows:w.writerow([r['writer_id'],r['name'],r['existing_status'],'; '.join(r['screening_flags']),'; '.join(r['curated_findings']),'pending',r['narrative_words'],r['book_cards']])
def link(i):
    route={82:'poet-dokana',257:'poet-drink',337:'poet-kshanika'}.get(i,f'poet-{i}')
    return f'[{name(i)}](http://127.0.0.1:8771/{route}.html)'
md=['---', 'type: "Review"', 'title: "Writer enrichment — doubt checklist"', '---', '', '# Writer enrichment — doubt checklist','', '**Status: audit screening complete; factual/editorial review remains open.** No biographies, books, poems or profiles were changed by this audit. The enrichment loop remains paused.','',f"All **{counts['profiles']} profile records** were screened against their evidence metadata. This covers about **{counts['narrative_words']:,} words** of generated section text and **{counts['book_cards']} book cards**. It is not a fresh external verification of every sentence. Targeted findings below compare reader wording with dossiers, plus selected primary-source rechecks.",'','- **91 profiles** already have limited source evidence.','- **68 profiles** have only indexed/search evidence recorded for every cited source (67 are nevertheless classified source-checked). This does not mean the information is false.','- **3 earlier profiles** lack recorded source-access methods; do not count these as index-only.','- These groups overlap: **161 distinct profiles** need evidence follow-up on these screening criteria.','- Four possible duplicate pairs mean **427 records must not be described as 427 verified distinct writers**.','',f"There are **{len(F)} specific review items across {len(manual_ids)} profiles** below. “First” means resolve identity or material wording first; “Follow-up” means evidence, source structure or editorial judgment. Neither label asserts fabrication.",'','## Review first','']
for priority in ['first','follow-up']:
    if priority=='follow-up':md+=['','## Evidence and editorial follow-up','']
    for f in F:
        if f['priority']!=priority:continue
        md += [f"- [ ] **{f['id']} — {f['title']}**  ", f"  {f['doubt']} **Action:** {f['recommended_action']}  ", '  '+ ' · '.join(link(i) for i in f['writer_ids'])]
md += ['','## How to use the flags','','Do not remove every flagged paragraph automatically. Resolve a question using an identity-matched primary source, or soften/attribute the claim; omit it if useful support cannot be established. Record the evidence and decision before closing an item. Preserve captured originals and existing translator credits. No writer has received independent factual clearance from this audit.','','The automatically generated poem commentary is **literary interpretation**, not author-approved biography. Keep a short, clearly scoped reading of the poems; avoid treating poetic speakers as autobiographical or extrapolating a whole career from one poem. Consider shortening these passages during our page review. This audit did not re-read every poem.','','## Already contained uncertainties — do not confuse with active errors','','The existing dossiers correctly withhold several claims: conflicting birth years for writers161 and372; unconfirmed death notice for71; inflated award wording for258; current-employment assertions for218; Ma Yongbo’s outside biography for423. Urna Bose152’s second-prize wording and Ratnamala Swain254’s translation roles were already handled cautiously. Their captured originals still need provenance-aware review, but an omitted claim is not an error in the new narrative.','','## Evidence and coverage','','[Detailed findings and all427 screening records](findings.json) · [Compact all-profile checklist](profile-screening.csv) · [Fresh source rechecks](source-rechecks.json) · [Prior91 source-limited follow-ups](../ENRICHMENT-COMPLETION.md)','','The earlier batch “verification passed” refers to build, integrity, route and rendering checks. It does **not** establish factual truth, source independence or author approval. “Source-checked” means some external support was found; a repeated contributor biography and an author’s self-description can share the same original claim.','','Executor: current assistant, Anvesha research / Drishti self-review; independent=false. User requested doubts to be flagged, not publication or wholesale rewriting.']
(OUT/'REVIEW-CHECKLIST.md').write_text('\n'.join(md)+'\n')
print(json.dumps(counts,indent=2))
