"""Research007: identity-checked narratives and poem-based introductions."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[5]; SITE=ROOT/'projects/site'; HOME=ROOT/'kb/research/writers'; DATE='2026-10-01'
def source(label,url,supports,access='opened_page'):
 return dict(label=label,url=url,supports=supports,access=access,accessed_on=DATE)
entries={
194:{'status':'source_limited_local_draft','paragraphs':[
'Ananya Goswami contributes Ashes to Kabita Live’s April 2023 edition. Her contributor note describes an enduring interest in art and literature; the poem itself offers a searching encounter with grief, survival and the difficult work of beginning again.',
'Waves, darkness and drifting ashes give suffering a landscape. The phoenix appears as a possibility, but the poem resists the comfort of an effortless rebirth. Its closing movement asks what it takes to go on living when the self must find a path through its own ruins.'
], 'sources':[], 'identity_match':'Writer194 is securely linked to poem182 locally. The short journal biography supplies no location, named book or professional affiliation to distinguish external namesakes.', 'poems_read':[182],
'limitations':['Exact-name, poem-title and distinctive biography-phrase searches did not establish an external identity. Same-name Medium, LinkedIn and student writing records are not joined.','No books, awards, employment or personal experience of suffering inferred from the poem.'], 'next_action':'Author/editor may supply a personal literary page or independently matching publication; contribution-based introduction remains a source-limited draft.'},
178:{'paragraphs':[
'Ajit Dash writes poetry in English, with interests that extend to language and public life. His contributor biography in Literary Vibes identifies the collections Midnight Dream and Wings of Burning Violin. The journal has also published his poems Sriram and Lotus.',
'In Kabita Live’s Mother Bharati, an invocation grows into a vision of cultural and civic renewal. Figures from the Ramayana and Mahabharata stand beside questions about language, learning and social hierarchy. The poem’s address to a mother figure gives these public concerns the cadence of an appeal.'
], 'sources':[source('Literary Vibes · April2026 poems and contributor note','https://positivevibes.today/article/newsview/634',['Ajit Dash poems Sriram and Lotus; contributor note identifies Midnight Dream (2017) and Wings of Burning Violin'])],
'identity_match':'Distinctive multilingualism/Odia pronunciation research description and freelance journalism in the external contributor note match the captured biography, beyond name alone.', 'poems_read':[157],
'limitations':['Book titles supported by literary contributor note only; publisher editions and purchase destinations not independently located.','Ancestry, global reputation, success claims and comparison with Yeats omitted as unsupported promotional claims.','Adjacent Aneek Chatterjee bibliography and awards are a different person and excluded. No political affiliation inferred from poetic themes.'], 'next_action':'Obtain publisher bibliography; independent author/editor factual review pending.'},
174:{'paragraphs':[
'Akhil Kumar Mishra writes poetry in Odia and English. His English collection Painted Silence was published by Timepass in 2018 and is catalogued by the Gandhi Smriti Library at LBSNAA. His work in public broadcasting has run alongside his literary interests; in March 2026, he presided over a Maya Sahitya gathering in Bhubaneswar devoted to literature and its place in society.',
'His Kabita Live poem ଅଧା ବାଟ turns towards a journey left unfinished. A green morning, an uneasy reflection and a mountain of sorrow on shifting sand bring hope and instability into the same space. The address to a companion who stopped halfway makes the distance emotional as well as physical.'
], 'books':[{'title':'Painted Silence','detail':'English poetry · Timepass, 2018','url':'https://gsl.lbsnaa.gov.in/cgi-bin/koha/opac-detail.pl?biblionumber=355975'}],
'sources':[source('Gandhi Smriti Library, LBSNAA · Painted Silence','https://gsl.lbsnaa.gov.in/cgi-bin/koha/opac-detail.pl?biblionumber=355975',['Author, Timepass2018, poetry, ISBN9789387563421'],'indexed_library_catalogue'),source('OdishaBytes · Painted Silence launch,2018','https://odishabytes.com/akhil-mishras-maiden-english-poetry-collection-painted-silence-released/amp/',['Bilingual poetry, first English collection, historical public broadcasting career'],'indexed_article_direct_open_failed'),source('Press Information Bureau · Maya Sahitya gathering, March2026','https://www.pib.gov.in/PressReleasePage.aspx?PRID=2234687&lang=2&reg=48',['Presided over literary gathering at NABM Bhubaneswar on2March2026'],'indexed_government_release_direct_open_failed')],
'identity_match':'Exact full name and Odia/English poetry match local biography; library author record, launch coverage and government literary-event record connect the writer and broadcasting career.', 'poems_read':[151],
'limitations':['Direct article and PIB retrieval failed; indexed full text available. Current job title and total collection count not asserted from historical reports.','Library catalogues title without The; launch report uses The Painted Silence. Native source poem remains unchanged.'], 'next_action':'Author/editor review; complete bibliography may be added when publisher records are available.'},
171:{'paragraphs':[
'Anindita Bose is a poet, editor and literary organiser associated with Kolkata. Her collections include I Know the Truth of a Broken Mirror and Illuminating Darkness. She co-edited The Kolkata Cadence with Jagari Mukherjee and Inam Hussain Mullick, bringing together contemporary voices from the city. Chair Poetry Evenings lists her as festival manager; its 2024 programme also records the launch of Youthful Elegies: Echoes of a New Generation 2024, which she edited.',
'Her Kabita Live poems return to the work of tending an inner life. Mrittika finds a grounding presence in soil and the living world, while Mothers’ Day on Earth measures longing through the absence of a mother’s physical presence. Path of Consciousness and Existence & Essence question how a self can stay rooted amid change; Fluttering Hearts gives that restless search a more defiant movement.'
], 'books':[{'title':'The Kolkata Cadence: Contemporary Kolkata Poets','detail':'Co-editor · Hawakal, 2021','url':'https://www.hawakal.com/books/english-books/poetry-english-books/the-kolkata-cadence-contemporary-kolkata-poets/'}],
'sources':[source('Hawakal · The Kolkata Cadence','https://www.hawakal.com/books/english-books/poetry-english-books/the-kolkata-cadence-contemporary-kolkata-poets/',['Three named coeditors; publication15January2021; ISBN9788194853893']),source('Chair Poetry Evenings · Festival team','https://www.chairpoetryevenings.org/about.html',['Anindita Bose listed as Festival Manager']),source('Chair Poetry Evenings ·2024 programme','https://www.chairpoetryevenings.org/2024.html',['Youthful Elegies edited by Anindita Bose; scheduled launch30November2024 and convenor role']),source('Google Books · Illuminating Darkness','https://books.google.com/books/about/Illuminating_Darkness.html?id=CKKi0AEACAAJ',['Ukiyoto2024 edition, ISBN9789361725777; publisher description connects earlier Broken Mirror collection'],'indexed_bibliographic_text_direct_open_failed')],
'identity_match':'Distinctive books, Kolkata literary organising and Chair Poetry role match captured biography, separating this writer from the actor and other namesakes.', 'poems_read':[816,615,610,365,162],
'limitations':['Captured Raa2020 title and Ukiyoto2024 record appear to concern different editions; no first-publication year assigned to Illuminating Darkness.','Broken Mirror publication year varies2017/2018 across accounts, so year omitted pending publisher confirmation.','Mother-loss speaker not converted into a personal bereavement claim. Festival role attributed to team listing rather than inferred permanent employment.','Only publisher-verified anthology added to book links; secondary bibliographic records remain references.'], 'next_action':'Author/editor to reconcile edition dates and full bibliography; independent review pending.'},
170:{'paragraphs':[
'Angurbala Parida is an Odia poet associated with Rourkela. Sahitya Akademi records her participation in its Asmita programme for Odia women writers in Bhubaneswar on 17 July 2013, where she read Rabana and Balada. The event placed her work in a conversation about women’s experience, identity and the pressures of social life.',
'In Kabita Live’s ନାରୀ ପରି ମରୁଥାଏ ନଈ, the river and the woman mirror one another: both sustain life, endure restraint and face the loss of a name. ପ୍ରେମ ସରିବା ଦିନ widens the question of love into a landscape of violence and ruins. Against that devastation, the continuing flow of the Kathajodi and Mahanadi offers a counter-image.'
], 'sources':[source('Sahitya Akademi · Asmita Odia Writers,2013','https://sahitya-akademi.gov.in/e-newsletter/July-Septmber_2013_Nesletter.pdf',['17July2013 reading, poems Rabana/Balada; PDF page49 (printed52)'],'opened_pdf'),source('Odisha Culture Department · Publishers’ Directory of Odisha','https://culture.odisha.gov.in/sites/default/files/2022-10/Pub_directory.pdf',['Exact name and Rourkela association; PDF page105'],'opened_pdf')],
'identity_match':'Exact full name and Rourkela connection in government directory match captured biography; Akademi programme establishes Odia literary practice.', 'poems_read':[780,152],
'limitations':['Sahitya Akademi event participation is not an award; unsupported wiki award claim excluded.','Book counts differ between captured biography and open wiki. No count, award or educational qualification added.','Publisher Urdhwa lead failed retrieval and is not presented as a verified book link. Historical directory not used as current home address.','Poem speakers, gender critique and violent imagery not treated as autobiographical facts.'], 'next_action':'Verify books from accessible publisher catalogue and obtain author/editor factual review.'}
}
if __name__=='__main__':
 profiles={p['id']:p for p in json.loads((SITE/'data/writer-profiles.json').read_text())}
 for ident,item in entries.items():
  current=json.loads((SITE/'data/writer-enrichment.json').read_text())
  if str(ident) in current: raise RuntimeError(f'Refuse overwrite {ident}')
  reader={'sections':[{'heading':'Life and writing.','language':'en','paragraphs':item['paragraphs']}],'books':item.get('books',[]),'sources':[{k:s[k] for k in ['label','url']} for s in item['sources']],'reviewed_on':DATE}
  record={'writer_id':ident,'name':profiles[ident]['name'],'reviewed_on':DATE,'batch':'research-007','status':item.get('status','source_checked_local_draft'),'independent':False,'portrait_action':'unchanged','reader_draft':reader,**{k:v for k,v in item.items() if k not in ['paragraphs','books','status']}}
  record['limitations'].append('Same-assistant research/interpretation; author/editor factual review pending.')
  (HOME/'enrichment'/f'{ident}.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n')
  current[str(ident)]=reader
  (SITE/'data/writer-enrichment.json').write_text(json.dumps(current,ensure_ascii=False,indent=2)+'\n')
  print('Saved writer',ident)
