from save_writer import save,source
save(186,dict(
 paragraphs=["Ranjita Panda writes poetry in Odia. In the poems gathered here, private suffering meets a wider unease about how people live with one another. ‘ମିଛମୁହଁ’ moves from news of disasters to the search for reassurance in ritual, prediction and the lines of a palm, before turning towards estrangement and deceit.","‘ସ୍ତୁପ’ gives lovelessness a physical landscape: displaced stars, an unhearing sky and a heap of suffering. Hunger and thirst make its questions immediate. Read together, these poems bring emotional vulnerability into contact with a world that offers no easy consolation."],
 sources=[],status='source_limited_local_draft',
 identity_match='Captured Odia byline and locally attributed original poems establish the reader narrative. Sahitya Akademi documents a poet of the same name from Sambalpur; local poem metadata names Sonepur. The literary and regional overlap is plausible but no distinctive book, poem or biography bridge was established, so event participation is not transferred into the reader biography.',
 poems_read=[dict(id=665,title='ମିଛମୁହଁ',coverage='Full original Odia poem, including ending; trailing address distinguished from poetic text.',basis='Disaster news, laboratory time, ritual and horoscope, palm manuscript, estranged city and familial deceit.'),dict(id=178,title='ସ୍ତୁପ',coverage='Full original Odia poem.',basis='Loveless death, displaced stars and moon, unheard lament, suffering heap, hunger, thirst and unanswered plea.')],
 limitations=['Captured six-anthology and one-novel counts lack named, independently matched bibliographic records; no titles or awards added.','Unreferenced birth date and personal details from Wikidata excluded.','Possible Sahitya Akademi namesake remains an identity lead rather than a confirmed biographical claim.'],
 research_leads=[dict(url='https://sahitya-akademi.gov.in/e-newsletter/July-Septmber_2013_Nesletter.pdf',finding='Opened official newsletter: page 48 (printed 52) records Ranjita Panda, poet from Sambalpur, reading Prema Karibasa at an Asmita programme. No exact local poem or biography bridge found.'),dict(url='https://hub.batoi.com/sachitrabijaya/publication/jan-2013-674d6550bf1e7',finding='Search-indexed publisher contents name Ranjita Panda; direct access failed. Name alone insufficient for a fuller biography.'),dict(url='https://www.wikidata.org/wiki/Q63255863',finding='Ranjeeta/Ranjita Panda aliases and native name, but personal statements have no references; not used.')],
 next_action='Ask author/editor to confirm bibliography and whether the 2013 Sahitya Akademi participant is this contributor; independent Odia close-reading review pending.'
))
