from save_writer import save,source
save(368,dict(
 paragraphs=['Raja Chakraborty grew up in Kolkata and writes in Bengali and English. He studied English literature at Calcutta University and also sketches and paints. His Bengali writing includes humorous and satirical rhymes, while his English collections include Whispers in the Wind and 65 Ways to Talk and Forget.', 'In “Crack”, a thin mark spreading across a wall becomes an image of two people drifting apart. Paint cannot hide old wounds, and remembered laughter cannot repair the fracture. The short lines allow an ordinary surface to carry the weight of an unspoken relationship.'],
 books=[dict(title='Whispers in the Wind',detail='English poetry; Hawakal.',url='https://www.hawakal.com/books/english-books/poetry-english-books/whispers-in-the-wind/'),dict(title='65 Ways to Talk and Forget',detail='Poetry; Penprints.',url='https://penprints.in/shop/product/65-ways-to-talk-and-forget-by-raja-chakraborty/')],
 sources=[source('Piker Press — Raja Chakraborty','https://www.pikerpress.com/author/307/raja-chakraborty','Contributor biography confirms Kolkata, Bengali/English poetry, Masters in English at Calcutta University, humorous Bengali rhyme and visual art.'),source('Hawakal — Whispers in the Wind','https://www.hawakal.com/books/english-books/poetry-english-books/whispers-in-the-wind/','Publisher names Raja Chakraborty and English poetry collection.'),source('Penprints — 65 Ways to Talk and Forget','https://penprints.in/shop/product/65-ways-to-talk-and-forget-by-raja-chakraborty/','Publisher names Raja Chakraborty and poetry collection.')],
 identity_match='Kolkata upbringing, bilingual Bengali/English writing, Bengali rhymes and English poetry agree across captured bio and Piker Press. Publisher titles match the literary author. Same-name pharmacy and anthropology academics not used.',
 poems_read=[dict(id=478,title='Crack',coverage='Complete original, both stanzas',basis='Wall crack and paint concealing old wounds turn to relationship fault lines and celluloid laughter; short lineation.')],
 limitations=['Piker Press contains internally different English-book counts, and capture has later larger totals; no comprehensive count asserted.','No inference that the relationship in Crack is autobiographical; no current employment claim.'],research_leads=[],next_action='Independent author/editor review of narrative and selected bibliography.'
))
