from save_writer import save,source
save(385,dict(
 paragraphs=['Rupa Rao is a poet and editor whose writing has appeared in Different Truths and Setu. Trained in business and law in Mumbai, she also brings writers together through poetry sessions and collaborative anthologies. With C. A. MacKenzie, she compiled Whispers of Spring’s Serenade, an English-language anthology published by MacKenzie Publishing.', '“Soundless Shrieks” centres children left vulnerable by war and displacement. Its movement from stunned silence to a direct appeal for compassion refuses to let children disappear into statistics. Repeated end sounds give urgency to the poem’s plea for shelter, security and peace.'],
 books=[dict(title='Whispers of Spring’s Serenade',detail='Poetry anthology, compiled with C. A. MacKenzie; MacKenzie Publishing. ISBN 9781990589409.',url='https://store.pothi.com/book/c-mackenzie-whispers-springs-serendade/')],
 sources=[source('Different Truths — Rupa Rao, Corrosive Connections','https://www.differenttruths.com/corrosive-connections/','Contributor biography: MBA and law from Mumbai, poetry and other creative work. Full relevant indexed text read; direct open returned cache miss.','search_index'),source('Setu — Rupa Rao, March 2025','https://www.setumag.com/2025/03/special-edition-rupa-rao.html','Contributor biography corroborates MBA/law, poetry hosting and anthology editing; direct open cache miss, indexed biography read.','search_index'),source('Pothi — Whispers of Spring’s Serenade','https://store.pothi.com/book/c-mackenzie-whispers-springs-serendade/','ISBN, publisher, compilation by Rupa and Cathy; title/body and contributor list inspected in index. Direct open cache miss.','search_index'),source('Aishwariya Laxmi — contribution to Whispers of Spring’s Serenade','https://aishwariyalaxmi.com/2025/06/04/whispers-of-springs-serenade/','Contributor names both compilers Rupa Rao and C. A. MacKenzie and links the same Pothi listing. Direct open cache miss; indexed post read.','search_index')],
 identity_match='Name, Mumbai MBA/law qualifications and poetry/anthology editing in captured bio agree with Different Truths and Setu biographies. Anthology credited by contributor and seller. Unrelated finance LinkedIn profile not used.',
 poems_read=[dict(id=524,title='Soundless Shrieks',coverage='Complete original, all five stanzas',basis='Orphans, soundless mourning, numerical enumeration, exposure to abuse and deprivation, final direct appeal to end conflict; repeated end sounds.')],
 limitations=['Direct opens failed for sources used; accessible indexed text and exact URLs recorded.','Four/five anthology counts differ with publication date; totals and current organizational titles omitted.','Statistics in the poem are literary source text, not independently checked current population estimates; no numbers repeated in narrative.','Pothi heading misspells Serenade as Serendade; body and contributor post agree on Serenade.'],research_leads=[],next_action='Independent editor to review narrative and confirm current bibliography; recheck direct source access when available.'
))
