"""Integrate supported narratives; uncertain external identities remain explicit."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[5];SITE=ROOT/'projects/site';HOME=ROOT/'kb/research/writers';DATE='2026-10-01'
def source(label,url,supports,access='opened_page'):
 return dict(label=label,url=url,supports=supports,access=access,accessed_on=DATE)
entries={
379:{'status':'source_limited_local_draft','paragraphs':[
'Anjali Pattnaik writes poetry in Odia. Her contributor note records publication in literary journals and magazines, and her Kabita Live poems move between intimate reflection and social satire.',
'In ମୁଁ ଯେବେ ନଈ ହେଇଯାଏ, the speaker becomes a river and then a drifting leaf, finding in their movement the vulnerability of love. ମୁଁ ଗୋଟେ ସାଧାରଣ ଲୋକ takes a sharply different voice: its self-described ordinary man exposes his own cruelty, dependence and indifference. The poem lets his repeated claim to ordinariness become an indictment.'
], 'sources':[], 'identity_match':'Local contributor and two poem memberships established; external StoryMirror identity lacks matching work or professional anchor.', 'poems_read':[634,500],
'leads':[source('StoryMirror · same-name Odia poetry listing','https://storymirror.com/read/oriya/poem/%E0%AC%B8%E0%AC%BF%E0%AC%AE%E0%AD%87%E0%AC%A3%E0%AD%8D%E0%AC%9F/tag',['Same-name Odia writer only; insufficient identity match'],'indexed_page_text')],
'limitations':['No independently verified collection, award or job claim. Poem500 includes an accounts-officer signature at Sambalpur, retained as evidence rather than a current appointment.','The abusive male speaker is a literary persona, not an assertion about the poet’s personal conduct or politics.','Do not merge with same-name medical researcher or administrative staff.'], 'next_action':'Confirm StoryMirror identity through matching work or author confirmation; seek a verified collection record.'},
369:{'paragraphs':[
'Afruja Akhtar is an Assamese poet, writer, translator and teacher associated with Duliajan. The MockingOwl Roost’s contributor note records her study of English and Assamese literature and places her within the journal’s international creative community.',
'Her Kabita Live poem Love in quest gathers clouds, dark wings and entwined hands into a brief encounter shaped by desire. Its movement towards memory and sweet deception unsettles the intimacy of its opening. The concentrated imagery carries the emotional turn without a long narrative explanation.'
], 'sources':[source('The MockingOwl Roost · Volume2 Issue3 contributor note','https://www.mockingowlroost.com/wp-content/uploads/2022/07/The-MockingOwl-Roost-Volume-2-Issue-3-Introspection.pdf',['Assamese poet/writer/translator, teacher, Duliajan and English/Assamese study'],'indexed_pdf_text_size_limit')],
'identity_match':'Exact name, Assamese writing, teacher profession, Duliajan and dual-language study agree with captured journal biography.', 'poems_read':[476],
'limitations':['Full PDF retrieval exceeded tool size limit; indexed contributor note read.','Sources differ in how they name the English degree institution; no university-specific credential asserted. Captured Assamese-degree sentence is incomplete.','Collection title has only the supplied romanization; publisher/year not independently verified. No inferred translator credit for Love in quest.','Toshali festival indexed schedule names her but page dates conflict; omit dated participation claim.'], 'next_action':'Verify Assamese collection title, publisher and degree details through primary records.'},
347:{'status':'source_limited_local_draft','paragraphs':[
'Aakash Nayak’s poem Skeleton appears in Kabita Live’s July 2024 edition. A serpent’s skeleton and an anthill form its small, shifting world: grains, insects and the spaces inside the remains become the poem’s points of attention.',
'As stars seem to emerge from an ant’s mouth, the scale opens from the minute to the vast. The closing insistence on luminosity brings light into a scene built from darkness and remains. The poem offers a distinctive introduction to the writer through image and transformation.'
], 'sources':[], 'identity_match':'Only local stable writer347 and poem432 can be established. Empty supplied biography; no confident external identity from exact name/title/text searches.', 'poems_read':[432],
'limitations':['This is a contribution-based introduction, not an independently sourced biography.','No birthplace, profession, language of composition beyond displayed English, awards or books inferred. Do not conflate with similarly named technology workers, tutors or actor Akash Dasnayak.'], 'next_action':'Obtain a contributor biography or a verified author/publication link; preserve existing portrait and local contribution.'},
330:{'paragraphs':[
'Abanindra Udgata writes in Odia and English after a career with the Reserve Bank of India. His contributor note places him in Bhubaneswar; a 2016 Impact Investors Council document records his role as Principal Chief General Manager in the bank’s Financial Inclusion and Development Department.',
'In Kabita Live, ଭୋକର ଅନ୍ୟନାମ lets hunger change shape, from familiar daily life to war, love and the writing of poetry. ସେଇ ଲୋକ ଜଣକ, a tribute to Ramakanta Rath, remembers the poet through trees, hills and recurring acts of recognition. Landscape becomes a way for a voice to remain present.'
], 'sources':[source('Impact Investors Council ·6 January2016 letter, p.1','https://iiic.in/wp-content/uploads/2021/01/IIC-Representation-to-Niti-Aayog-6Jan16.pdf',['Historical Principal CGM/FIDD/RBI role'],'opened_pdf')],
'identity_match':'Exact full name and highly specific RBI role corroborate the journal note; Bhubaneswar remains attributed to that note. No connection to Srinibash Udgata inferred.', 'poems_read':[689,560,406],
'limitations':['No dated retirement claim beyond journal statement; historical2016 title is not presented as current.','Unnamed competition awards and anthology totals omitted pending literary sources.','No RBI salary table or personal contact details reproduced.'], 'next_action':'Find verified collection and anthology records; retain supported historical professional context.'},
323:{'paragraphs':[
'Anish Kanjilal is a Kolkata-based poet and educator. His collections include Fateless 13, published by Partridge, and 11 Oracles, published by White Falcon Publishing. His work draws on myth and spiritual imagery to examine human choices, loss and survival.',
'Kabita Live’s The Last Faith brings the wooden form of Jagannath into conversation with ecological destruction and figures from several religious and mythic traditions. The Man in White returns to a repeated chorus as light, winter and bodily endurance change around its central figure. Both poems give abstract questions a strongly visual setting.'
], 'books':[{'title':'Fateless 13: A Collection of 13 Poems','detail':'Poetry · Partridge','url':'https://www.partridgepublishing.com/en-in/bookstore/bookdetails/626069-Fateless-13'},{'title':'11 Oracles','detail':'Poetry · White Falcon Publishing,2022','url':'https://authoranishkanjilal.com/book-review-11-oracles-by-anish-kanjilal/'}],
'sources':[source('Partridge · Fateless13','https://www.partridgepublishing.com/en-in/bookstore/bookdetails/626069-Fateless-13',['Title, author and English teaching; publication date19 September2014']),source('Author website ·11 Oracles','https://authoranishkanjilal.com/book-review-11-oracles-by-anish-kanjilal/',['Kolkata identity, books and educator context']),source('White Falcon Publishing ·2022 book announcement','https://www.abnewswire.com/pressreleases/anish-kanjilal-launches-his-second-book-11-oracles-a-collection-of-11-soulful-hymns_620022.html',['Publisher-origin announcement of11 Oracles'],'indexed_press_release')],
'identity_match':'Exact name, Kolkata, educator profession and both named collections agree with preserved contributor note and author/publisher pages.', 'poems_read':[396,663],
'limitations':['Fateless13 publisher lists19 September2014; contributor and publicity copy say2015. Omit year in reader copy pending reconciliation rather than silently treating publicity as authoritative.','Awards have inconsistent years and lack organizer corroboration; omitted.','11 Oracles2024 French edition is distinct from2022 English original. Publisher product listing found but direct retrieval failed; selected-book link uses accessible author page.','Literary discussion describes poem imagery, not personal religious belief.'], 'next_action':'Reconcile Fateless13 publication year with the author; verify any award claims before inclusion.'}
}
if __name__=='__main__':
 profiles={p['id']:p for p in json.loads((SITE/'data/writer-profiles.json').read_text())};current=json.loads((SITE/'data/writer-enrichment.json').read_text())
 for ident,item in entries.items():
  if str(ident) in current:raise RuntimeError(f'Refuse overwrite {ident}')
  reader={'sections':[{'heading':'Life and writing.','language':'en','paragraphs':item['paragraphs']}],'books':item.get('books',[]),'sources':[{k:s[k] for k in ['label','url']} for s in item['sources']],'reviewed_on':DATE}
  record={'writer_id':ident,'name':profiles[ident]['name'],'reviewed_on':DATE,'batch':'research-004','status':item.get('status','source_checked_local_draft'),'independent':False,'portrait_action':'unchanged','reader_draft':reader,**{k:v for k,v in item.items() if k not in ['paragraphs','books','status']}}
  record['limitations'].append('Same-assistant research/interpretation; author/editor factual review pending.')
  (HOME/'enrichment'/f'{ident}.json').write_text(json.dumps(record,ensure_ascii=False,indent=2)+'\n');current[str(ident)]=reader;(SITE/'data/writer-enrichment.json').write_text(json.dumps(current,ensure_ascii=False,indent=2)+'\n');print('Saved writer',ident)
