from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]; M=R/json.loads((R/'utkal.config.json').read_text())['paths']['primary_design_source']
(R/'kb/assets').mkdir(parents=True,exist_ok=True)
def wrap(kind,title,body):return '---\ntype: '+json.dumps(kind)+'\ntitle: '+json.dumps(title)+'\n---\n\n'+body
(R/'kb/reference/design-system.md').write_text(wrap('Design reference','Approved design system', 'Derived from [the canonical KB design source](../artifacts/design/brand-guide/DESIGN-SYSTEM.md); edit that source and regenerate.\n\n'+(R/'kb/artifacts/design/brand-guide/DESIGN-SYSTEM.md').read_text()))
data=json.loads((M/'site/assets/icons/earth-voice-v1/manifest.json').read_text())
(R/'kb/assets/icon-catalogue.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
total=len(data['icons']);editorial=sum(i['family']=='editorial' for i in data['icons']);utility=total-editorial
lines=['# Kabita Live · reusable icon catalogue','',f'**Option A single-colour treatment approved.** The four footer-* motifs are approved and applied; other symbols retain their individual statuses below. {total} original SVG symbols. Source: the primary design manifest; regenerate this view after editing.','','Review: http://127.0.0.1:8771/icon-atelier.html . Ink is selected. Earth exports are retained as historical comparisons.','','| ID | Symbol | Intended use | Cultural / poetic story | Status |','|---|---|---|---|---|']
for i in data['icons']:lines.append('| '+ ' | '.join([i['id'],i['name'],i['use'],i['story'],i.get('status','candidate')])+' |')
lines += ['','## Reuse rules','',f'- {editorial} editorial motifs: 48-unit masters, use at 36–72px. {utility} utility symbols: 24-unit masters, use at 20–24px in targets of at least 44px. Approved footer icons use24px and1.35px strokes.','- Use one colour per icon. Footer symbols inherit ink; later approved reading actions and selected editorial marks use theme-aware laterite. Multicolour studies remain historical. Keep labels beside unfamiliar motifs and controls.','- Preserve the existing logo and header separator. No decorative marks beside every paragraph or verse.','- Cultural references are interpretations, not certified weave patterns, ritual diagrams or botanical/topographic evidence.','- Keep Pipili Chandua reserved. Famous writers belong in sourced portraits and biographies, not generic action glyphs.','- The public SVG sprite and manifest live under site/assets/icons/earth-voice-v1. Original geometry was drawn for Kabita Live; no third-party icon paths were copied.','- No shared external icon repository has been connected. The project catalogue is the starting library the user requested.','','## Next batch to consider','','Only if a real page needs them: issue/calendar, contributor/poet, download, print, language/translation, text-size, filter/reset, check/error and previous/back. These are backlog suggestions, not claims of finished assets. Existing familiar controls can remain until reviewed.']
(R/'kb/assets/icon-catalogue.md').write_text(wrap('Asset catalogue','Reusable icon catalogue','\n'.join(lines)+'\n'))
print(f'Design reference and {total}-icon knowledge catalogue synchronized.')
